// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: stats/v1/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompletedHabits      int32                  `protobuf:"varint,2,opt,name=completed_habits,json=completedHabits,proto3" json:"completed_habits,omitempty"`
	CompletedRoutines    int32                  `protobuf:"varint,3,opt,name=completed_routines,json=completedRoutines,proto3" json:"completed_routines,omitempty"`
	CurrentHabitStreak   int32                  `protobuf:"varint,4,opt,name=current_habit_streak,json=currentHabitStreak,proto3" json:"current_habit_streak,omitempty"`
	LongestHabitStreak   int32                  `protobuf:"varint,5,opt,name=longest_habit_streak,json=longestHabitStreak,proto3" json:"longest_habit_streak,omitempty"`
	CurrentRoutineStreak int32                  `protobuf:"varint,6,opt,name=current_routine_streak,json=currentRoutineStreak,proto3" json:"current_routine_streak,omitempty"`
	LongestRoutineStreak int32                  `protobuf:"varint,7,opt,name=longest_routine_streak,json=longestRoutineStreak,proto3" json:"longest_routine_streak,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserStats) Reset() {
	*x = UserStats{}
	mi := &file_stats_v1_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStats) ProtoMessage() {}

func (x *UserStats) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStats.ProtoReflect.Descriptor instead.
func (*UserStats) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{0}
}

func (x *UserStats) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStats) GetCompletedHabits() int32 {
	if x != nil {
		return x.CompletedHabits
	}
	return 0
}

func (x *UserStats) GetCompletedRoutines() int32 {
	if x != nil {
		return x.CompletedRoutines
	}
	return 0
}

func (x *UserStats) GetCurrentHabitStreak() int32 {
	if x != nil {
		return x.CurrentHabitStreak
	}
	return 0
}

func (x *UserStats) GetLongestHabitStreak() int32 {
	if x != nil {
		return x.LongestHabitStreak
	}
	return 0
}

func (x *UserStats) GetCurrentRoutineStreak() int32 {
	if x != nil {
		return x.CurrentRoutineStreak
	}
	return 0
}

func (x *UserStats) GetLongestRoutineStreak() int32 {
	if x != nil {
		return x.LongestRoutineStreak
	}
	return 0
}

func (x *UserStats) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserStats) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserStatsRequest) Reset() {
	*x = CreateUserStatsRequest{}
	mi := &file_stats_v1_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserStatsRequest) ProtoMessage() {}

func (x *CreateUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserStatsRequest.ProtoReflect.Descriptor instead.
func (*CreateUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateUserStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *UserStats             `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserStatsResponse) Reset() {
	*x = CreateUserStatsResponse{}
	mi := &file_stats_v1_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserStatsResponse) ProtoMessage() {}

func (x *CreateUserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserStatsResponse.ProtoReflect.Descriptor instead.
func (*CreateUserStatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserStatsResponse) GetStats() *UserStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	mi := &file_stats_v1_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *UserStats             `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsResponse) Reset() {
	*x = GetUserStatsResponse{}
	mi := &file_stats_v1_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsResponse) ProtoMessage() {}

func (x *GetUserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsResponse.ProtoReflect.Descriptor instead.
func (*GetUserStatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserStatsResponse) GetStats() *UserStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type DeleteUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserStatsRequest) Reset() {
	*x = DeleteUserStatsRequest{}
	mi := &file_stats_v1_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserStatsRequest) ProtoMessage() {}

func (x *DeleteUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserStatsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserStatsResponse) Reset() {
	*x = DeleteUserStatsResponse{}
	mi := &file_stats_v1_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserStatsResponse) ProtoMessage() {}

func (x *DeleteUserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserStatsResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserStatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RegisterHabitCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HabitId       string                 `protobuf:"bytes,2,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHabitCompletionRequest) Reset() {
	*x = RegisterHabitCompletionRequest{}
	mi := &file_stats_v1_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHabitCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHabitCompletionRequest) ProtoMessage() {}

func (x *RegisterHabitCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHabitCompletionRequest.ProtoReflect.Descriptor instead.
func (*RegisterHabitCompletionRequest) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterHabitCompletionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterHabitCompletionRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *RegisterHabitCompletionRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type RegisterHabitCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHabitCompletionResponse) Reset() {
	*x = RegisterHabitCompletionResponse{}
	mi := &file_stats_v1_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHabitCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHabitCompletionResponse) ProtoMessage() {}

func (x *RegisterHabitCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHabitCompletionResponse.ProtoReflect.Descriptor instead.
func (*RegisterHabitCompletionResponse) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterHabitCompletionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UndoHabitCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HabitId       string                 `protobuf:"bytes,2,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndoHabitCompletionRequest) Reset() {
	*x = UndoHabitCompletionRequest{}
	mi := &file_stats_v1_stats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndoHabitCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoHabitCompletionRequest) ProtoMessage() {}

func (x *UndoHabitCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoHabitCompletionRequest.ProtoReflect.Descriptor instead.
func (*UndoHabitCompletionRequest) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{9}
}

func (x *UndoHabitCompletionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UndoHabitCompletionRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *UndoHabitCompletionRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type UndoHabitCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndoHabitCompletionResponse) Reset() {
	*x = UndoHabitCompletionResponse{}
	mi := &file_stats_v1_stats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndoHabitCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoHabitCompletionResponse) ProtoMessage() {}

func (x *UndoHabitCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoHabitCompletionResponse.ProtoReflect.Descriptor instead.
func (*UndoHabitCompletionResponse) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{10}
}

func (x *UndoHabitCompletionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RegisterRoutineCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoutineId     string                 `protobuf:"bytes,2,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRoutineCompletionRequest) Reset() {
	*x = RegisterRoutineCompletionRequest{}
	mi := &file_stats_v1_stats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRoutineCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRoutineCompletionRequest) ProtoMessage() {}

func (x *RegisterRoutineCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRoutineCompletionRequest.ProtoReflect.Descriptor instead.
func (*RegisterRoutineCompletionRequest) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterRoutineCompletionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterRoutineCompletionRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

func (x *RegisterRoutineCompletionRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type RegisterRoutineCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRoutineCompletionResponse) Reset() {
	*x = RegisterRoutineCompletionResponse{}
	mi := &file_stats_v1_stats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRoutineCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRoutineCompletionResponse) ProtoMessage() {}

func (x *RegisterRoutineCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRoutineCompletionResponse.ProtoReflect.Descriptor instead.
func (*RegisterRoutineCompletionResponse) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterRoutineCompletionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UndoRoutineCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoutineId     string                 `protobuf:"bytes,2,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndoRoutineCompletionRequest) Reset() {
	*x = UndoRoutineCompletionRequest{}
	mi := &file_stats_v1_stats_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndoRoutineCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoRoutineCompletionRequest) ProtoMessage() {}

func (x *UndoRoutineCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoRoutineCompletionRequest.ProtoReflect.Descriptor instead.
func (*UndoRoutineCompletionRequest) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{13}
}

func (x *UndoRoutineCompletionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UndoRoutineCompletionRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

func (x *UndoRoutineCompletionRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type UndoRoutineCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndoRoutineCompletionResponse) Reset() {
	*x = UndoRoutineCompletionResponse{}
	mi := &file_stats_v1_stats_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndoRoutineCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoRoutineCompletionResponse) ProtoMessage() {}

func (x *UndoRoutineCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoRoutineCompletionResponse.ProtoReflect.Descriptor instead.
func (*UndoRoutineCompletionResponse) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_proto_rawDescGZIP(), []int{14}
}

func (x *UndoRoutineCompletionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_stats_v1_stats_proto protoreflect.FileDescriptor

const file_stats_v1_stats_proto_rawDesc = "" +
	"\n" +
	"\x14stats/v1/stats.proto\x12\x05stats\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x03\n" +
	"\tUserStats\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10completed_habits\x18\x02 \x01(\x05R\x0fcompletedHabits\x12-\n" +
	"\x12completed_routines\x18\x03 \x01(\x05R\x11completedRoutines\x120\n" +
	"\x14current_habit_streak\x18\x04 \x01(\x05R\x12currentHabitStreak\x120\n" +
	"\x14longest_habit_streak\x18\x05 \x01(\x05R\x12longestHabitStreak\x124\n" +
	"\x16current_routine_streak\x18\x06 \x01(\x05R\x14currentRoutineStreak\x124\n" +
	"\x16longest_routine_streak\x18\a \x01(\x05R\x14longestRoutineStreak\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"1\n" +
	"\x16CreateUserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x17CreateUserStatsResponse\x12&\n" +
	"\x05stats\x18\x01 \x01(\v2\x10.stats.UserStatsR\x05stats\".\n" +
	"\x13GetUserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\">\n" +
	"\x14GetUserStatsResponse\x12&\n" +
	"\x05stats\x18\x01 \x01(\v2\x10.stats.UserStatsR\x05stats\"1\n" +
	"\x16DeleteUserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"3\n" +
	"\x17DeleteUserStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x93\x01\n" +
	"\x1eRegisterHabitCompletionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bhabit_id\x18\x02 \x01(\tR\ahabitId\x12=\n" +
	"\fcompleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\";\n" +
	"\x1fRegisterHabitCompletionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8f\x01\n" +
	"\x1aUndoHabitCompletionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bhabit_id\x18\x02 \x01(\tR\ahabitId\x12=\n" +
	"\fcompleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"7\n" +
	"\x1bUndoHabitCompletionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x99\x01\n" +
	" RegisterRoutineCompletionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x02 \x01(\tR\troutineId\x12=\n" +
	"\fcompleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"=\n" +
	"!RegisterRoutineCompletionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x95\x01\n" +
	"\x1cUndoRoutineCompletionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x02 \x01(\tR\troutineId\x12=\n" +
	"\fcompleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"9\n" +
	"\x1dUndoRoutineCompletionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x97\x05\n" +
	"\fStatsService\x12P\n" +
	"\x0fCreateUserStats\x12\x1d.stats.CreateUserStatsRequest\x1a\x1e.stats.CreateUserStatsResponse\x12G\n" +
	"\fGetUserStats\x12\x1a.stats.GetUserStatsRequest\x1a\x1b.stats.GetUserStatsResponse\x12P\n" +
	"\x0fDeleteUserStats\x12\x1d.stats.DeleteUserStatsRequest\x1a\x1e.stats.DeleteUserStatsResponse\x12h\n" +
	"\x17RegisterHabitCompletion\x12%.stats.RegisterHabitCompletionRequest\x1a&.stats.RegisterHabitCompletionResponse\x12\\\n" +
	"\x13UndoHabitCompletion\x12!.stats.UndoHabitCompletionRequest\x1a\".stats.UndoHabitCompletionResponse\x12n\n" +
	"\x19RegisterRoutineCompletion\x12'.stats.RegisterRoutineCompletionRequest\x1a(.stats.RegisterRoutineCompletionResponse\x12b\n" +
	"\x15UndoRoutineCompletion\x12#.stats.UndoRoutineCompletionRequest\x1a$.stats.UndoRoutineCompletionResponseB\n" +
	"Z\bpb/statsb\x06proto3"

var (
	file_stats_v1_stats_proto_rawDescOnce sync.Once
	file_stats_v1_stats_proto_rawDescData []byte
)

func file_stats_v1_stats_proto_rawDescGZIP() []byte {
	file_stats_v1_stats_proto_rawDescOnce.Do(func() {
		file_stats_v1_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_v1_stats_proto_rawDesc), len(file_stats_v1_stats_proto_rawDesc)))
	})
	return file_stats_v1_stats_proto_rawDescData
}

var file_stats_v1_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_stats_v1_stats_proto_goTypes = []any{
	(*UserStats)(nil),                         // 0: stats.UserStats
	(*CreateUserStatsRequest)(nil),            // 1: stats.CreateUserStatsRequest
	(*CreateUserStatsResponse)(nil),           // 2: stats.CreateUserStatsResponse
	(*GetUserStatsRequest)(nil),               // 3: stats.GetUserStatsRequest
	(*GetUserStatsResponse)(nil),              // 4: stats.GetUserStatsResponse
	(*DeleteUserStatsRequest)(nil),            // 5: stats.DeleteUserStatsRequest
	(*DeleteUserStatsResponse)(nil),           // 6: stats.DeleteUserStatsResponse
	(*RegisterHabitCompletionRequest)(nil),    // 7: stats.RegisterHabitCompletionRequest
	(*RegisterHabitCompletionResponse)(nil),   // 8: stats.RegisterHabitCompletionResponse
	(*UndoHabitCompletionRequest)(nil),        // 9: stats.UndoHabitCompletionRequest
	(*UndoHabitCompletionResponse)(nil),       // 10: stats.UndoHabitCompletionResponse
	(*RegisterRoutineCompletionRequest)(nil),  // 11: stats.RegisterRoutineCompletionRequest
	(*RegisterRoutineCompletionResponse)(nil), // 12: stats.RegisterRoutineCompletionResponse
	(*UndoRoutineCompletionRequest)(nil),      // 13: stats.UndoRoutineCompletionRequest
	(*UndoRoutineCompletionResponse)(nil),     // 14: stats.UndoRoutineCompletionResponse
	(*timestamppb.Timestamp)(nil),             // 15: google.protobuf.Timestamp
}
var file_stats_v1_stats_proto_depIdxs = []int32{
	15, // 0: stats.UserStats.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: stats.UserStats.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: stats.CreateUserStatsResponse.stats:type_name -> stats.UserStats
	0,  // 3: stats.GetUserStatsResponse.stats:type_name -> stats.UserStats
	15, // 4: stats.RegisterHabitCompletionRequest.completed_at:type_name -> google.protobuf.Timestamp
	15, // 5: stats.UndoHabitCompletionRequest.completed_at:type_name -> google.protobuf.Timestamp
	15, // 6: stats.RegisterRoutineCompletionRequest.completed_at:type_name -> google.protobuf.Timestamp
	15, // 7: stats.UndoRoutineCompletionRequest.completed_at:type_name -> google.protobuf.Timestamp
	1,  // 8: stats.StatsService.CreateUserStats:input_type -> stats.CreateUserStatsRequest
	3,  // 9: stats.StatsService.GetUserStats:input_type -> stats.GetUserStatsRequest
	5,  // 10: stats.StatsService.DeleteUserStats:input_type -> stats.DeleteUserStatsRequest
	7,  // 11: stats.StatsService.RegisterHabitCompletion:input_type -> stats.RegisterHabitCompletionRequest
	9,  // 12: stats.StatsService.UndoHabitCompletion:input_type -> stats.UndoHabitCompletionRequest
	11, // 13: stats.StatsService.RegisterRoutineCompletion:input_type -> stats.RegisterRoutineCompletionRequest
	13, // 14: stats.StatsService.UndoRoutineCompletion:input_type -> stats.UndoRoutineCompletionRequest
	2,  // 15: stats.StatsService.CreateUserStats:output_type -> stats.CreateUserStatsResponse
	4,  // 16: stats.StatsService.GetUserStats:output_type -> stats.GetUserStatsResponse
	6,  // 17: stats.StatsService.DeleteUserStats:output_type -> stats.DeleteUserStatsResponse
	8,  // 18: stats.StatsService.RegisterHabitCompletion:output_type -> stats.RegisterHabitCompletionResponse
	10, // 19: stats.StatsService.UndoHabitCompletion:output_type -> stats.UndoHabitCompletionResponse
	12, // 20: stats.StatsService.RegisterRoutineCompletion:output_type -> stats.RegisterRoutineCompletionResponse
	14, // 21: stats.StatsService.UndoRoutineCompletion:output_type -> stats.UndoRoutineCompletionResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_stats_v1_stats_proto_init() }
func file_stats_v1_stats_proto_init() {
	if File_stats_v1_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_v1_stats_proto_rawDesc), len(file_stats_v1_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_v1_stats_proto_goTypes,
		DependencyIndexes: file_stats_v1_stats_proto_depIdxs,
		MessageInfos:      file_stats_v1_stats_proto_msgTypes,
	}.Build()
	File_stats_v1_stats_proto = out.File
	file_stats_v1_stats_proto_goTypes = nil
	file_stats_v1_stats_proto_depIdxs = nil
}
