// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: stats/v1/stats.proto

package stats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatsService_CreateUserStats_FullMethodName           = "/stats.StatsService/CreateUserStats"
	StatsService_GetUserStats_FullMethodName              = "/stats.StatsService/GetUserStats"
	StatsService_DeleteUserStats_FullMethodName           = "/stats.StatsService/DeleteUserStats"
	StatsService_RegisterHabitCompletion_FullMethodName   = "/stats.StatsService/RegisterHabitCompletion"
	StatsService_UndoHabitCompletion_FullMethodName       = "/stats.StatsService/UndoHabitCompletion"
	StatsService_RegisterRoutineCompletion_FullMethodName = "/stats.StatsService/RegisterRoutineCompletion"
	StatsService_UndoRoutineCompletion_FullMethodName     = "/stats.StatsService/UndoRoutineCompletion"
)

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsServiceClient interface {
	CreateUserStats(ctx context.Context, in *CreateUserStatsRequest, opts ...grpc.CallOption) (*CreateUserStatsResponse, error)
	GetUserStats(ctx context.Context, in *GetUserStatsRequest, opts ...grpc.CallOption) (*GetUserStatsResponse, error)
	DeleteUserStats(ctx context.Context, in *DeleteUserStatsRequest, opts ...grpc.CallOption) (*DeleteUserStatsResponse, error)
	RegisterHabitCompletion(ctx context.Context, in *RegisterHabitCompletionRequest, opts ...grpc.CallOption) (*RegisterHabitCompletionResponse, error)
	UndoHabitCompletion(ctx context.Context, in *UndoHabitCompletionRequest, opts ...grpc.CallOption) (*UndoHabitCompletionResponse, error)
	RegisterRoutineCompletion(ctx context.Context, in *RegisterRoutineCompletionRequest, opts ...grpc.CallOption) (*RegisterRoutineCompletionResponse, error)
	UndoRoutineCompletion(ctx context.Context, in *UndoRoutineCompletionRequest, opts ...grpc.CallOption) (*UndoRoutineCompletionResponse, error)
}

type statsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServiceClient(cc grpc.ClientConnInterface) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) CreateUserStats(ctx context.Context, in *CreateUserStatsRequest, opts ...grpc.CallOption) (*CreateUserStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserStatsResponse)
	err := c.cc.Invoke(ctx, StatsService_CreateUserStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetUserStats(ctx context.Context, in *GetUserStatsRequest, opts ...grpc.CallOption) (*GetUserStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserStatsResponse)
	err := c.cc.Invoke(ctx, StatsService_GetUserStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) DeleteUserStats(ctx context.Context, in *DeleteUserStatsRequest, opts ...grpc.CallOption) (*DeleteUserStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserStatsResponse)
	err := c.cc.Invoke(ctx, StatsService_DeleteUserStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) RegisterHabitCompletion(ctx context.Context, in *RegisterHabitCompletionRequest, opts ...grpc.CallOption) (*RegisterHabitCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterHabitCompletionResponse)
	err := c.cc.Invoke(ctx, StatsService_RegisterHabitCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) UndoHabitCompletion(ctx context.Context, in *UndoHabitCompletionRequest, opts ...grpc.CallOption) (*UndoHabitCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndoHabitCompletionResponse)
	err := c.cc.Invoke(ctx, StatsService_UndoHabitCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) RegisterRoutineCompletion(ctx context.Context, in *RegisterRoutineCompletionRequest, opts ...grpc.CallOption) (*RegisterRoutineCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterRoutineCompletionResponse)
	err := c.cc.Invoke(ctx, StatsService_RegisterRoutineCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) UndoRoutineCompletion(ctx context.Context, in *UndoRoutineCompletionRequest, opts ...grpc.CallOption) (*UndoRoutineCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndoRoutineCompletionResponse)
	err := c.cc.Invoke(ctx, StatsService_UndoRoutineCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
// All implementations must embed UnimplementedStatsServiceServer
// for forward compatibility.
type StatsServiceServer interface {
	CreateUserStats(context.Context, *CreateUserStatsRequest) (*CreateUserStatsResponse, error)
	GetUserStats(context.Context, *GetUserStatsRequest) (*GetUserStatsResponse, error)
	DeleteUserStats(context.Context, *DeleteUserStatsRequest) (*DeleteUserStatsResponse, error)
	RegisterHabitCompletion(context.Context, *RegisterHabitCompletionRequest) (*RegisterHabitCompletionResponse, error)
	UndoHabitCompletion(context.Context, *UndoHabitCompletionRequest) (*UndoHabitCompletionResponse, error)
	RegisterRoutineCompletion(context.Context, *RegisterRoutineCompletionRequest) (*RegisterRoutineCompletionResponse, error)
	UndoRoutineCompletion(context.Context, *UndoRoutineCompletionRequest) (*UndoRoutineCompletionResponse, error)
	mustEmbedUnimplementedStatsServiceServer()
}

// UnimplementedStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatsServiceServer struct{}

func (UnimplementedStatsServiceServer) CreateUserStats(context.Context, *CreateUserStatsRequest) (*CreateUserStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserStats not implemented")
}
func (UnimplementedStatsServiceServer) GetUserStats(context.Context, *GetUserStatsRequest) (*GetUserStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserStats not implemented")
}
func (UnimplementedStatsServiceServer) DeleteUserStats(context.Context, *DeleteUserStatsRequest) (*DeleteUserStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserStats not implemented")
}
func (UnimplementedStatsServiceServer) RegisterHabitCompletion(context.Context, *RegisterHabitCompletionRequest) (*RegisterHabitCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterHabitCompletion not implemented")
}
func (UnimplementedStatsServiceServer) UndoHabitCompletion(context.Context, *UndoHabitCompletionRequest) (*UndoHabitCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UndoHabitCompletion not implemented")
}
func (UnimplementedStatsServiceServer) RegisterRoutineCompletion(context.Context, *RegisterRoutineCompletionRequest) (*RegisterRoutineCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterRoutineCompletion not implemented")
}
func (UnimplementedStatsServiceServer) UndoRoutineCompletion(context.Context, *UndoRoutineCompletionRequest) (*UndoRoutineCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UndoRoutineCompletion not implemented")
}
func (UnimplementedStatsServiceServer) mustEmbedUnimplementedStatsServiceServer() {}
func (UnimplementedStatsServiceServer) testEmbeddedByValue()                      {}

// UnsafeStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServiceServer will
// result in compilation errors.
type UnsafeStatsServiceServer interface {
	mustEmbedUnimplementedStatsServiceServer()
}

func RegisterStatsServiceServer(s grpc.ServiceRegistrar, srv StatsServiceServer) {
	// If the following call panics, it indicates UnimplementedStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatsService_ServiceDesc, srv)
}

func _StatsService_CreateUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).CreateUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_CreateUserStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).CreateUserStats(ctx, req.(*CreateUserStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetUserStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetUserStats(ctx, req.(*GetUserStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_DeleteUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).DeleteUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_DeleteUserStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).DeleteUserStats(ctx, req.(*DeleteUserStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_RegisterHabitCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterHabitCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).RegisterHabitCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_RegisterHabitCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).RegisterHabitCompletion(ctx, req.(*RegisterHabitCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_UndoHabitCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndoHabitCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).UndoHabitCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_UndoHabitCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).UndoHabitCompletion(ctx, req.(*UndoHabitCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_RegisterRoutineCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRoutineCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).RegisterRoutineCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_RegisterRoutineCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).RegisterRoutineCompletion(ctx, req.(*RegisterRoutineCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_UndoRoutineCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndoRoutineCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).UndoRoutineCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_UndoRoutineCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).UndoRoutineCompletion(ctx, req.(*UndoRoutineCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsService_ServiceDesc is the grpc.ServiceDesc for StatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserStats",
			Handler:    _StatsService_CreateUserStats_Handler,
		},
		{
			MethodName: "GetUserStats",
			Handler:    _StatsService_GetUserStats_Handler,
		},
		{
			MethodName: "DeleteUserStats",
			Handler:    _StatsService_DeleteUserStats_Handler,
		},
		{
			MethodName: "RegisterHabitCompletion",
			Handler:    _StatsService_RegisterHabitCompletion_Handler,
		},
		{
			MethodName: "UndoHabitCompletion",
			Handler:    _StatsService_UndoHabitCompletion_Handler,
		},
		{
			MethodName: "RegisterRoutineCompletion",
			Handler:    _StatsService_RegisterRoutineCompletion_Handler,
		},
		{
			MethodName: "UndoRoutineCompletion",
			Handler:    _StatsService_UndoRoutineCompletion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/v1/stats.proto",
}
