// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type UserStat struct {
	UserID               uuid.UUID
	CompletedHabits      int32
	CompletedRoutines    int32
	CurrentHabitStreak   int32
	LongestHabitStreak   int32
	CurrentRoutineStreak int32
	LongestRoutineStreak int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
}
