// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserStats = `-- name: CreateUserStats :one
INSERT INTO user_stats(user_id)
VALUES ($1) RETURNING user_id, completed_habits, completed_routines, current_habit_streak, longest_habit_streak, current_routine_streak, longest_routine_streak, created_at, updated_at
`

func (q *Queries) CreateUserStats(ctx context.Context, userID uuid.UUID) (UserStat, error) {
	row := q.db.QueryRowContext(ctx, createUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.CompletedHabits,
		&i.CompletedRoutines,
		&i.CurrentHabitStreak,
		&i.LongestHabitStreak,
		&i.CurrentRoutineStreak,
		&i.LongestRoutineStreak,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementCompletedHabits = `-- name: DecrementCompletedHabits :exec
UPDATE user_stats
SET completed_habits = GREATEST(completed_habits - 1, 0),
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) DecrementCompletedHabits(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementCompletedHabits, id)
	return err
}

const decrementCompletedRoutines = `-- name: DecrementCompletedRoutines :exec
UPDATE user_stats
SET completed_routines = GREATEST(completed_routines - 1, 0),
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) DecrementCompletedRoutines(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementCompletedRoutines, id)
	return err
}

const deleteUserStats = `-- name: DeleteUserStats :exec
DELETE 
FROM user_stats 
WHERE user_id = $1
`

func (q *Queries) DeleteUserStats(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserStats, userID)
	return err
}

const getUserStats = `-- name: GetUserStats :one
SELECT user_id, completed_habits, completed_routines, current_habit_streak, longest_habit_streak, current_routine_streak, longest_routine_streak, created_at, updated_at FROM user_stats 
WHERE user_id = $1
`

func (q *Queries) GetUserStats(ctx context.Context, userID uuid.UUID) (UserStat, error) {
	row := q.db.QueryRowContext(ctx, getUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.CompletedHabits,
		&i.CompletedRoutines,
		&i.CurrentHabitStreak,
		&i.LongestHabitStreak,
		&i.CurrentRoutineStreak,
		&i.LongestRoutineStreak,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementCompletedHabits = `-- name: IncrementCompletedHabits :exec
UPDATE user_stats
SET completed_habits = completed_habits + 1,
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) IncrementCompletedHabits(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementCompletedHabits, id)
	return err
}

const incrementCompletedRoutines = `-- name: IncrementCompletedRoutines :exec
UPDATE user_stats
SET completed_routines = completed_routines + 1,
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) IncrementCompletedRoutines(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementCompletedRoutines, id)
	return err
}

const updateHabitStreaks = `-- name: UpdateHabitStreaks :exec
UPDATE user_stats
SET current_habit_streak = $1,
    longest_habit_streak = $2,
    updated_at = NOW()
WHERE user_id = $3
`

type UpdateHabitStreaksParams struct {
	CurrentHabitStreak int32
	LongestHabitStreak int32
	ID                 uuid.UUID
}

func (q *Queries) UpdateHabitStreaks(ctx context.Context, arg UpdateHabitStreaksParams) error {
	_, err := q.db.ExecContext(ctx, updateHabitStreaks, arg.CurrentHabitStreak, arg.LongestHabitStreak, arg.ID)
	return err
}

const updateRoutineStreaks = `-- name: UpdateRoutineStreaks :exec
UPDATE user_stats
SET longest_routine_streak = $1,
    current_routine_streak = $2,
    updated_at = NOW()
WHERE user_id = $3
`

type UpdateRoutineStreaksParams struct {
	LongestRoutineStreak int32
	CurrentRoutineStreak int32
	ID                   uuid.UUID
}

func (q *Queries) UpdateRoutineStreaks(ctx context.Context, arg UpdateRoutineStreaksParams) error {
	_, err := q.db.ExecContext(ctx, updateRoutineStreaks, arg.LongestRoutineStreak, arg.CurrentRoutineStreak, arg.ID)
	return err
}
