version: "3.9"

services:
  redis:
    image: redis:7
    restart: unless-stopped

  auth-service:
    restart: unless-stopped

    build:
      context: ${ROUTE_DOCKER}/auth-service
      dockerfile: Dockerfile

    env_file:
      - ${ROUTE_DOCKER}/auth-service/.env

    depends_on:
      - redis

  user-service:
    restart: unless-stopped

    build:
      context: ${ROUTE_ROOT}
      dockerfile: backend/services/user-service/Dockerfile

    env_file:
      - ${ROUTE_DOCKER}/user-service/.env

  social-service:
    restart: unless-stopped

    build:
      context: ${ROUTE_ROOT}
      dockerfile: backend/services/social-service/Dockerfile

    env_file:
      - ${ROUTE_DOCKER}/social-service/.env

    depends_on:
      - user-service

  habit-service:
    restart: unless-stopped

    build:
      context: ${ROUTE_ROOT}
      dockerfile: backend/services/habit-service/Dockerfile

    env_file:
      - ${ROUTE_DOCKER}/habit-service/.env

    depends_on:
      - user-service

  stats-service:
    restart: unless-stopped

    build:
      context: ${ROUTE_ROOT}
      dockerfile: backend/services/stats-service/Dockerfile

    env_file:
      - ${ROUTE_DOCKER}/stats-service/.env

    depends_on:
      - habit-service
      - user-service

  nginx:
    restart: unless-stopped

    build:
      context: ../../nginx
      dockerfile: Dockerfile

    ports:
      - "80:80"

    depends_on:
      - auth-service
      - user-service
      - social-service
      - habit-service
      - stats-service