services:
  redis:
    image: redis:7
    restart: unless-stopped

  auth-service:
    restart: unless-stopped

    build:
      context: ${ROUTE_DOCKER}/auth-service
      dockerfile: Dockerfile

    env_file:
      - ${ROUTE_DOCKER}/auth-service/.env

    depends_on:
      - redis

  user-service:
    restart: unless-stopped

    build:
      context: ${ROUTE_ROOT}
      dockerfile: backend/services/user-service/Dockerfile

    env_file:
      - ${ROUTE_DOCKER}/user-service/.env

    environment:
      SERVICE_NAME: user-service
      TYPE: tcp
      PORT: ":8080"

  social-service:
    restart: unless-stopped

    build:
      context: ${ROUTE_ROOT}
      dockerfile: backend/services/social-service/Dockerfile

    env_file:
      - ${ROUTE_DOCKER}/social-service/.env

    environment:
      SERVICE_NAME: social-service
      TYPE: tcp
      PORT: ":8081"

    depends_on:
      - user-service

  habit-service:
    restart: unless-stopped

    build:
      context: ${ROUTE_ROOT}
      dockerfile: backend/services/habit-service/Dockerfile

    env_file:
      - ${ROUTE_DOCKER}/habit-service/.env

    environment:
      SERVICE_NAME: habit-service
      TYPE: tcp
      PORT: ":8082"

    depends_on:
      - user-service

  stats-service:
    restart: unless-stopped

    build:
      context: ${ROUTE_ROOT}
      dockerfile: backend/services/stats-service/Dockerfile

    env_file:
      - ${ROUTE_DOCKER}/stats-service/.env

    environment:
      SERVICE_NAME: stats-service
      TYPE: tcp
      PORT: ":8083"

    depends_on:
      - habit-service
      - user-service

  gateway:
    restart: unless-stopped

    build:
      context: ${ROUTE_ROOT}/backend
      dockerfile: gateway/Dockerfile

    env_file:
      - ${ROUTE_ROOT}/backend/gateway/.env

    environment:
      SERVICE_NAME: gateway
      PORT: ":8084"
      USER_SERVICE_ADDR: user-service:8080
      TLS_CA_CERT_PATH: /app/cert/ca-cert.pem

    depends_on:
      - user-service

    ports:
      - "8084:8084/tcp"

  frontend:
    restart: unless-stopped

    build:
      context: ${ROUTE_ROOT}/frontend
      dockerfile: Dockerfile

    ports:
      - "4200:80/tcp"

  nginx:
    restart: unless-stopped

    build:
      context: ../../nginx
      dockerfile: Dockerfile

    ports:
      - "80:80/tcp"

    depends_on:
      - auth-service
      - gateway