// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

// tá mt simples, oq add dps:
// talvez 2 ou mais tabelas, uma de empresa e uma pra email separados, ainda mais pq algm pode ter conta corporativa e normal
// mudar o delete pra q n delete o user pra sempre
// tlvz verificação por CNPJ pra casos de empresas
// enviar email na hr de criar conta pro email
// e pra parte de empresa pensar melhor, mt coisa talvez pra adicionar

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
}
