// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID    uuid.UUID
	Name  string
	Email string
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, name, email
FROM users
WHERE id = ANY($1::uuid[])
`

type GetUsersByIDsRow struct {
	ID    uuid.UUID
	Name  string
	Email string
}

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetUsersByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByIDsRow
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUser = `-- name: SearchUser :many
SELECT id, name, email
FROM users
WHERE
    (name ILIKE '%' || $1 || '%' OR $1 = '')
  AND
    (email ILIKE '%' || $2 || '%' OR $2 = '')
    LIMIT 20
`

type SearchUserParams struct {
	Name  sql.NullString
	Email sql.NullString
}

type SearchUserRow struct {
	ID    uuid.UUID
	Name  string
	Email string
}

func (q *Queries) SearchUser(ctx context.Context, arg SearchUserParams) ([]SearchUserRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUser, arg.Name, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUserRow
	for rows.Next() {
		var i SearchUserRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password = $1
WHERE id = $2
`

type UpdatePasswordParams struct {
	Password string
	ID       uuid.UUID
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.Password, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    name = COALESCE($1, name),
    email = COALESCE($2, email)
WHERE id = $3
`

type UpdateUserParams struct {
	Name  string
	Email string
	ID    uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Name, arg.Email, arg.ID)
	return err
}
