// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID    int32
	Name  string
	Email string
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const listFollowers = `-- name: ListFollowers :many
SELECT u.id, u.name, u.email
FROM followers f
         JOIN users u ON u.id = f.follower_id
WHERE f.followee_id = ?
`

type ListFollowersRow struct {
	ID    int32
	Name  string
	Email string
}

func (q *Queries) ListFollowers(ctx context.Context, followeeID int32) ([]ListFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowers, followeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowersRow
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT u.id, u.name, u.email
FROM followers f
         JOIN users u ON u.id = f.followee_id
WHERE f.follower_id = ?
`

type ListFollowingRow struct {
	ID    int32
	Name  string
	Email string
}

func (q *Queries) ListFollowing(ctx context.Context, followerID int32) ([]ListFollowingRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowing, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingRow
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUser = `-- name: SearchUser :many
SELECT id, name, email
FROM users
WHERE ( ? IS NULL OR name LIKE ? )
  AND ( ? IS NULL OR email LIKE ? )
`

type SearchUserParams struct {
	Column1 interface{}
	Name    string
	Column3 interface{}
	Email   string
}

type SearchUserRow struct {
	ID    int32
	Name  string
	Email string
}

func (q *Queries) SearchUser(ctx context.Context, arg SearchUserParams) ([]SearchUserRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUser,
		arg.Column1,
		arg.Name,
		arg.Column3,
		arg.Email,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUserRow
	for rows.Next() {
		var i SearchUserRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startFollowing = `-- name: StartFollowing :exec
INSERT INTO followers (follower_id, followee_id)
VALUES (?, ?)
`

type StartFollowingParams struct {
	FollowerID int32
	FolloweeID int32
}

func (q *Queries) StartFollowing(ctx context.Context, arg StartFollowingParams) error {
	_, err := q.db.ExecContext(ctx, startFollowing, arg.FollowerID, arg.FolloweeID)
	return err
}

const unfollow = `-- name: Unfollow :exec
DELETE FROM followers
WHERE follower_id = ? AND followee_id = ?
`

type UnfollowParams struct {
	FollowerID int32
	FolloweeID int32
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.ExecContext(ctx, unfollow, arg.FollowerID, arg.FolloweeID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password = ?
WHERE id = ?
`

type UpdatePasswordParams struct {
	Password string
	ID       int32
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.Password, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = COALESCE(?, name),
    email = COALESCE(?, email)
WHERE id = ?
`

type UpdateUserParams struct {
	Name  string
	Email string
	ID    int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Name, arg.Email, arg.ID)
	return err
}
