upstream auth_service {
    server auth-service:3000;
}

upstream gateway_service {
    server gateway:8084;
}

server {

    listen 80;

    # adicionar outras rotas finais dps

    location /api/v1/auth/ {
        rewrite ^/api/v1/auth/?(.*)$ /auth/$1 break;
        proxy_pass http://auth_service;
    }

    location /api/v1/user/ {
        proxy_pass http://gateway_service;
    }

    location /api/v1/social/ {
        proxy_pass http://gateway_service;
    }

    location /api/v1/habit/ {
        proxy_pass http://gateway_service;
    }

    location /api/v1/routine/ {
        proxy_pass http://gateway_service;
    }

    location /api/v1/stats/ {
        proxy_pass http://gateway_service;
    }

}