// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/social/social.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Follow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int32                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    int32                  `protobuf:"varint,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Follow) Reset() {
	*x = Follow{}
	mi := &file_proto_social_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Follow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Follow) ProtoMessage() {}

func (x *Follow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Follow.ProtoReflect.Descriptor instead.
func (*Follow) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{0}
}

func (x *Follow) GetFollowerId() int32 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *Follow) GetFolloweeId() int32 {
	if x != nil {
		return x.FolloweeId
	}
	return 0
}

type StartFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int32                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    int32                  `protobuf:"varint,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFollowingRequest) Reset() {
	*x = StartFollowingRequest{}
	mi := &file_proto_social_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFollowingRequest) ProtoMessage() {}

func (x *StartFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFollowingRequest.ProtoReflect.Descriptor instead.
func (*StartFollowingRequest) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{1}
}

func (x *StartFollowingRequest) GetFollowerId() int32 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *StartFollowingRequest) GetFolloweeId() int32 {
	if x != nil {
		return x.FolloweeId
	}
	return 0
}

type StartFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFollowingResponse) Reset() {
	*x = StartFollowingResponse{}
	mi := &file_proto_social_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFollowingResponse) ProtoMessage() {}

func (x *StartFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFollowingResponse.ProtoReflect.Descriptor instead.
func (*StartFollowingResponse) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{2}
}

func (x *StartFollowingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnfollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int32                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    int32                  `protobuf:"varint,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_proto_social_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowRequest) GetFollowerId() int32 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *UnfollowRequest) GetFolloweeId() int32 {
	if x != nil {
		return x.FolloweeId
	}
	return 0
}

type UnfollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowResponse) Reset() {
	*x = UnfollowResponse{}
	mi := &file_proto_social_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResponse) ProtoMessage() {}

func (x *UnfollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResponse.ProtoReflect.Descriptor instead.
func (*UnfollowResponse) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{4}
}

func (x *UnfollowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowersRequest) Reset() {
	*x = ListFollowersRequest{}
	mi := &file_proto_social_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowersRequest) ProtoMessage() {}

func (x *ListFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowersRequest.ProtoReflect.Descriptor instead.
func (*ListFollowersRequest) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{5}
}

func (x *ListFollowersRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerIds   []int32                `protobuf:"varint,1,rep,packed,name=follower_ids,json=followerIds,proto3" json:"follower_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowersResponse) Reset() {
	*x = ListFollowersResponse{}
	mi := &file_proto_social_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowersResponse) ProtoMessage() {}

func (x *ListFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowersResponse.ProtoReflect.Descriptor instead.
func (*ListFollowersResponse) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{6}
}

func (x *ListFollowersResponse) GetFollowerIds() []int32 {
	if x != nil {
		return x.FollowerIds
	}
	return nil
}

type ListFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingRequest) Reset() {
	*x = ListFollowingRequest{}
	mi := &file_proto_social_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingRequest) ProtoMessage() {}

func (x *ListFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingRequest.ProtoReflect.Descriptor instead.
func (*ListFollowingRequest) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{7}
}

func (x *ListFollowingRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowingIds  []int32                `protobuf:"varint,1,rep,packed,name=following_ids,json=followingIds,proto3" json:"following_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingResponse) Reset() {
	*x = ListFollowingResponse{}
	mi := &file_proto_social_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingResponse) ProtoMessage() {}

func (x *ListFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_social_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingResponse.ProtoReflect.Descriptor instead.
func (*ListFollowingResponse) Descriptor() ([]byte, []int) {
	return file_proto_social_social_proto_rawDescGZIP(), []int{8}
}

func (x *ListFollowingResponse) GetFollowingIds() []int32 {
	if x != nil {
		return x.FollowingIds
	}
	return nil
}

var File_proto_social_social_proto protoreflect.FileDescriptor

const file_proto_social_social_proto_rawDesc = "" +
	"\n" +
	"\x19proto/social/social.proto\x12\x06social\"J\n" +
	"\x06Follow\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x05R\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\x05R\n" +
	"followeeId\"Y\n" +
	"\x15StartFollowingRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x05R\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\x05R\n" +
	"followeeId\"2\n" +
	"\x16StartFollowingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"S\n" +
	"\x0fUnfollowRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x05R\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\x05R\n" +
	"followeeId\",\n" +
	"\x10UnfollowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x14ListFollowersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\":\n" +
	"\x15ListFollowersResponse\x12!\n" +
	"\ffollower_ids\x18\x01 \x03(\x05R\vfollowerIds\"/\n" +
	"\x14ListFollowingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"<\n" +
	"\x15ListFollowingResponse\x12#\n" +
	"\rfollowing_ids\x18\x01 \x03(\x05R\ffollowingIds2\xbb\x02\n" +
	"\rSocialService\x12O\n" +
	"\x0eStartFollowing\x12\x1d.social.StartFollowingRequest\x1a\x1e.social.StartFollowingResponse\x12=\n" +
	"\bUnfollow\x12\x17.social.UnfollowRequest\x1a\x18.social.UnfollowResponse\x12L\n" +
	"\rListFollowers\x12\x1c.social.ListFollowersRequest\x1a\x1d.social.ListFollowersResponse\x12L\n" +
	"\rListFollowing\x12\x1c.social.ListFollowingRequest\x1a\x1d.social.ListFollowingResponseB\rZ\v./pb/socialb\x06proto3"

var (
	file_proto_social_social_proto_rawDescOnce sync.Once
	file_proto_social_social_proto_rawDescData []byte
)

func file_proto_social_social_proto_rawDescGZIP() []byte {
	file_proto_social_social_proto_rawDescOnce.Do(func() {
		file_proto_social_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_social_social_proto_rawDesc), len(file_proto_social_social_proto_rawDesc)))
	})
	return file_proto_social_social_proto_rawDescData
}

var file_proto_social_social_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_social_social_proto_goTypes = []any{
	(*Follow)(nil),                 // 0: social.Follow
	(*StartFollowingRequest)(nil),  // 1: social.StartFollowingRequest
	(*StartFollowingResponse)(nil), // 2: social.StartFollowingResponse
	(*UnfollowRequest)(nil),        // 3: social.UnfollowRequest
	(*UnfollowResponse)(nil),       // 4: social.UnfollowResponse
	(*ListFollowersRequest)(nil),   // 5: social.ListFollowersRequest
	(*ListFollowersResponse)(nil),  // 6: social.ListFollowersResponse
	(*ListFollowingRequest)(nil),   // 7: social.ListFollowingRequest
	(*ListFollowingResponse)(nil),  // 8: social.ListFollowingResponse
}
var file_proto_social_social_proto_depIdxs = []int32{
	1, // 0: social.SocialService.StartFollowing:input_type -> social.StartFollowingRequest
	3, // 1: social.SocialService.Unfollow:input_type -> social.UnfollowRequest
	5, // 2: social.SocialService.ListFollowers:input_type -> social.ListFollowersRequest
	7, // 3: social.SocialService.ListFollowing:input_type -> social.ListFollowingRequest
	2, // 4: social.SocialService.StartFollowing:output_type -> social.StartFollowingResponse
	4, // 5: social.SocialService.Unfollow:output_type -> social.UnfollowResponse
	6, // 6: social.SocialService.ListFollowers:output_type -> social.ListFollowersResponse
	8, // 7: social.SocialService.ListFollowing:output_type -> social.ListFollowingResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_social_social_proto_init() }
func file_proto_social_social_proto_init() {
	if File_proto_social_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_social_social_proto_rawDesc), len(file_proto_social_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_social_social_proto_goTypes,
		DependencyIndexes: file_proto_social_social_proto_depIdxs,
		MessageInfos:      file_proto_social_social_proto_msgTypes,
	}.Build()
	File_proto_social_social_proto = out.File
	file_proto_social_social_proto_goTypes = nil
	file_proto_social_social_proto_depIdxs = nil
}
