upstream auth_service {
    server auth-service:3000;
}

upstream user_service {
    server user-service:8080;
}

upstream social_service {
    server social-service:8081;
}

upstream habit_service {
    server habit-service:8082;
}

server {

    listen 80;

    # adicionar outras rotas finais dps

    location /api/v1/auth/ {
        proxy_pass http://auth_service;
    }

    location /api/v1/users/ {
        proxy_pass http://user_service;
    }

    location /api/v1/social/ {
        proxy_pass http://social_service;
    }

    location /api/v1/habits/ {
        proxy_pass http://habit_service;
    }

}