// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Habit struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description sql.NullString
	ImageUrl    sql.NullString
	CreatedAt   time.Time
}

type HabitLog struct {
	ID          uuid.UUID
	HabitID     uuid.UUID
	CompletedAt time.Time
}

type Routine struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	CreatedAt time.Time
}

type RoutineHabit struct {
	RoutineID uuid.UUID
	HabitID   uuid.UUID
}
