// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Habit struct {
	ID          int32
	UserID      int32
	Name        string
	Description sql.NullString
	ImageUrl    sql.NullString
	CreatedAt   sql.NullTime
}

type HabitLog struct {
	ID          int32
	HabitID     int32
	CompletedAt sql.NullTime
}

type Routine struct {
	ID        int32
	UserID    int32
	Name      string
	CreatedAt sql.NullTime
}

type RoutineHabit struct {
	RoutineID int32
	HabitID   int32
}
