// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addHabitToRoutine = `-- name: AddHabitToRoutine :exec
INSERT INTO routine_habits (routine_id, habit_id)
VALUES (?, ?)
`

type AddHabitToRoutineParams struct {
	RoutineID int32
	HabitID   int32
}

func (q *Queries) AddHabitToRoutine(ctx context.Context, arg AddHabitToRoutineParams) error {
	_, err := q.db.ExecContext(ctx, addHabitToRoutine, arg.RoutineID, arg.HabitID)
	return err
}

const createHabit = `-- name: CreateHabit :execresult
INSERT INTO habits (user_id, name, description, image_url)
VALUES (?, ?, ?, ?)
`

type CreateHabitParams struct {
	UserID      int32
	Name        string
	Description sql.NullString
	ImageUrl    sql.NullString
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHabit,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
	)
}

const createRoutine = `-- name: CreateRoutine :execresult
INSERT INTO routines (user_id, name)
VALUES (?, ?)
`

type CreateRoutineParams struct {
	UserID int32
	Name   string
}

func (q *Queries) CreateRoutine(ctx context.Context, arg CreateRoutineParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRoutine, arg.UserID, arg.Name)
}

const deleteHabit = `-- name: DeleteHabit :exec
DELETE FROM habits
WHERE id = ?
`

func (q *Queries) DeleteHabit(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteHabit, id)
	return err
}

const deleteRoutine = `-- name: DeleteRoutine :exec
DELETE FROM routines
WHERE id = ?
`

func (q *Queries) DeleteRoutine(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteRoutine, id)
	return err
}

const getHabitByID = `-- name: GetHabitByID :one
SELECT id, user_id, name, description, image_url, created_at
FROM habits
WHERE id = ?
`

func (q *Queries) GetHabitByID(ctx context.Context, id int32) (Habit, error) {
	row := q.db.QueryRowContext(ctx, getHabitByID, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getHabitLogs = `-- name: GetHabitLogs :many
SELECT habit_id, completed_at
FROM habit_logs
WHERE habit_id = ?
  AND completed_at BETWEEN ? AND ?
ORDER BY completed_at DESC
`

type GetHabitLogsParams struct {
	HabitID         int32
	FromCompletedAt sql.NullTime
	ToCompletedAt   sql.NullTime
}

type GetHabitLogsRow struct {
	HabitID     int32
	CompletedAt sql.NullTime
}

func (q *Queries) GetHabitLogs(ctx context.Context, arg GetHabitLogsParams) ([]GetHabitLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getHabitLogs, arg.HabitID, arg.FromCompletedAt, arg.ToCompletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHabitLogsRow
	for rows.Next() {
		var i GetHabitLogsRow
		if err := rows.Scan(&i.HabitID, &i.CompletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoutineByID = `-- name: GetRoutineByID :one
SELECT id, user_id, name, created_at
FROM routines
WHERE id = ?
`

func (q *Queries) GetRoutineByID(ctx context.Context, id int32) (Routine, error) {
	row := q.db.QueryRowContext(ctx, getRoutineByID, id)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listHabitsByRoutine = `-- name: ListHabitsByRoutine :many
SELECT h.id, h.user_id, h.name, h.description, h.image_url, h.created_at
FROM habits h
         JOIN routine_habits rh ON rh.habit_id = h.id
WHERE rh.routine_id = ?
`

func (q *Queries) ListHabitsByRoutine(ctx context.Context, routineID int32) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, listHabitsByRoutine, routineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabitsByUser = `-- name: ListHabitsByUser :many
SELECT id, user_id, name, description, image_url, created_at
FROM habits
WHERE user_id = ?
`

func (q *Queries) ListHabitsByUser(ctx context.Context, userID int32) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, listHabitsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutinesByHabit = `-- name: ListRoutinesByHabit :many
SELECT r.id, r.user_id, r.name, r.created_at
FROM routines r
         JOIN routine_habits rh ON rh.routine_id = r.id
WHERE rh.habit_id = ?
`

func (q *Queries) ListRoutinesByHabit(ctx context.Context, habitID int32) ([]Routine, error) {
	rows, err := q.db.QueryContext(ctx, listRoutinesByHabit, habitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routine
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutinesByUser = `-- name: ListRoutinesByUser :many
SELECT id, user_id, name, created_at
FROM routines
WHERE user_id = ?
`

func (q *Queries) ListRoutinesByUser(ctx context.Context, userID int32) ([]Routine, error) {
	rows, err := q.db.QueryContext(ctx, listRoutinesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routine
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHabitCompleted = `-- name: MarkHabitCompleted :exec
INSERT INTO habit_logs (habit_id, completed_at)
VALUES (?, ?)
    ON DUPLICATE KEY UPDATE completed_at = completed_at
`

type MarkHabitCompletedParams struct {
	HabitID     int32
	CompletedAt sql.NullTime
}

func (q *Queries) MarkHabitCompleted(ctx context.Context, arg MarkHabitCompletedParams) error {
	_, err := q.db.ExecContext(ctx, markHabitCompleted, arg.HabitID, arg.CompletedAt)
	return err
}

const removeHabitFromRoutine = `-- name: RemoveHabitFromRoutine :exec
DELETE FROM routine_habits
WHERE routine_id = ? AND habit_id = ?
`

type RemoveHabitFromRoutineParams struct {
	RoutineID int32
	HabitID   int32
}

func (q *Queries) RemoveHabitFromRoutine(ctx context.Context, arg RemoveHabitFromRoutineParams) error {
	_, err := q.db.ExecContext(ctx, removeHabitFromRoutine, arg.RoutineID, arg.HabitID)
	return err
}

const unmarkHabitCompleted = `-- name: UnmarkHabitCompleted :exec
DELETE FROM habit_logs
WHERE habit_id = ?
  AND DATE(completed_at) = DATE(?)
`

type UnmarkHabitCompletedParams struct {
	HabitID int32
	DATE    time.Time
}

func (q *Queries) UnmarkHabitCompleted(ctx context.Context, arg UnmarkHabitCompletedParams) error {
	_, err := q.db.ExecContext(ctx, unmarkHabitCompleted, arg.HabitID, arg.DATE)
	return err
}

const updateHabit = `-- name: UpdateHabit :exec
UPDATE habits
SET name        = COALESCE(?, name),
    description = COALESCE(?, description),
    image_url   = COALESCE(?, image_url)
WHERE id = ?
`

type UpdateHabitParams struct {
	Name        string
	Description sql.NullString
	ImageUrl    sql.NullString
	ID          int32
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) error {
	_, err := q.db.ExecContext(ctx, updateHabit,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.ID,
	)
	return err
}

const updateRoutine = `-- name: UpdateRoutine :exec
UPDATE routines
SET name = COALESCE(?, name)
WHERE id = ?
`

type UpdateRoutineParams struct {
	Name string
	ID   int32
}

func (q *Queries) UpdateRoutine(ctx context.Context, arg UpdateRoutineParams) error {
	_, err := q.db.ExecContext(ctx, updateRoutine, arg.Name, arg.ID)
	return err
}
