// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addHabitToRoutine = `-- name: AddHabitToRoutine :exec
INSERT INTO routine_habits (routine_id, habit_id)
VALUES ($1, $2)
`

type AddHabitToRoutineParams struct {
	RoutineID uuid.UUID
	HabitID   uuid.UUID
}

func (q *Queries) AddHabitToRoutine(ctx context.Context, arg AddHabitToRoutineParams) error {
	_, err := q.db.ExecContext(ctx, addHabitToRoutine, arg.RoutineID, arg.HabitID)
	return err
}

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (user_id,
                    name,
                    description,
                    image_url,
                    created_at)
VALUES ($1,
        $2,
        $3,
        $4,
        NOW()) RETURNING id, user_id, name, description, image_url, created_at
`

type CreateHabitParams struct {
	UserID      uuid.UUID
	Name        string
	Description sql.NullString
	ImageUrl    sql.NullString
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRowContext(ctx, createHabit,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createRoutine = `-- name: CreateRoutine :one
INSERT INTO routines (user_id, name)
VALUES ($1, $2) RETURNING id, user_id, name, created_at
`

type CreateRoutineParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error) {
	row := q.db.QueryRowContext(ctx, createRoutine, arg.UserID, arg.Name)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHabit = `-- name: DeleteHabit :exec
DELETE
FROM habits
WHERE id = $1
`

func (q *Queries) DeleteHabit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteHabit, id)
	return err
}

const deleteRoutine = `-- name: DeleteRoutine :exec
DELETE
FROM routines
WHERE id = $1
`

func (q *Queries) DeleteRoutine(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRoutine, id)
	return err
}

const getHabitByID = `-- name: GetHabitByID :one
SELECT id, user_id, name, description, image_url, created_at
FROM habits
WHERE id = $1
`

func (q *Queries) GetHabitByID(ctx context.Context, id uuid.UUID) (Habit, error) {
	row := q.db.QueryRowContext(ctx, getHabitByID, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getHabitLogs = `-- name: GetHabitLogs :many
SELECT habit_id, completed_at
FROM habit_logs
WHERE habit_id = $1
  AND completed_at BETWEEN $2 AND $3
ORDER BY completed_at DESC
`

type GetHabitLogsParams struct {
	HabitID       uuid.UUID
	CompletedAt   time.Time
	CompletedAt_2 time.Time
}

type GetHabitLogsRow struct {
	HabitID     uuid.UUID
	CompletedAt time.Time
}

func (q *Queries) GetHabitLogs(ctx context.Context, arg GetHabitLogsParams) ([]GetHabitLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getHabitLogs, arg.HabitID, arg.CompletedAt, arg.CompletedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHabitLogsRow
	for rows.Next() {
		var i GetHabitLogsRow
		if err := rows.Scan(&i.HabitID, &i.CompletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoutineByID = `-- name: GetRoutineByID :one
SELECT id, user_id, name, created_at
FROM routines
WHERE id = $1
`

func (q *Queries) GetRoutineByID(ctx context.Context, id uuid.UUID) (Routine, error) {
	row := q.db.QueryRowContext(ctx, getRoutineByID, id)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listHabitsByRoutine = `-- name: ListHabitsByRoutine :many
SELECT h.id,
       h.user_id,
       h.name,
       h.description,
       h.image_url,
       h.created_at
FROM habits h
         JOIN routine_habits rh ON rh.habit_id = h.id
WHERE rh.routine_id = $1
`

func (q *Queries) ListHabitsByRoutine(ctx context.Context, routineID uuid.UUID) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, listHabitsByRoutine, routineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabitsByUser = `-- name: ListHabitsByUser :many
SELECT id, user_id, name, description, image_url, created_at
FROM habits
WHERE user_id = $1
`

func (q *Queries) ListHabitsByUser(ctx context.Context, userID uuid.UUID) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, listHabitsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutinesByHabit = `-- name: ListRoutinesByHabit :many
SELECT r.id,
       r.user_id,
       r.name,
       r.created_at
FROM routines r
         JOIN routine_habits rh ON rh.routine_id = r.id
WHERE rh.habit_id = $1
`

func (q *Queries) ListRoutinesByHabit(ctx context.Context, habitID uuid.UUID) ([]Routine, error) {
	rows, err := q.db.QueryContext(ctx, listRoutinesByHabit, habitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routine
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutinesByUser = `-- name: ListRoutinesByUser :many
SELECT id, user_id, name, created_at
FROM routines
WHERE user_id = $1
`

func (q *Queries) ListRoutinesByUser(ctx context.Context, userID uuid.UUID) ([]Routine, error) {
	rows, err := q.db.QueryContext(ctx, listRoutinesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routine
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHabitCompleted = `-- name: MarkHabitCompleted :exec
INSERT INTO habit_logs (habit_id, completed_at)
VALUES ($1, $2) ON CONFLICT (habit_id, completed_at) DO NOTHING
`

type MarkHabitCompletedParams struct {
	HabitID     uuid.UUID
	CompletedAt time.Time
}

func (q *Queries) MarkHabitCompleted(ctx context.Context, arg MarkHabitCompletedParams) error {
	_, err := q.db.ExecContext(ctx, markHabitCompleted, arg.HabitID, arg.CompletedAt)
	return err
}

const removeHabitFromRoutine = `-- name: RemoveHabitFromRoutine :exec
DELETE
FROM routine_habits
WHERE routine_id = $1
  AND habit_id = $2
`

type RemoveHabitFromRoutineParams struct {
	RoutineID uuid.UUID
	HabitID   uuid.UUID
}

func (q *Queries) RemoveHabitFromRoutine(ctx context.Context, arg RemoveHabitFromRoutineParams) error {
	_, err := q.db.ExecContext(ctx, removeHabitFromRoutine, arg.RoutineID, arg.HabitID)
	return err
}

const unmarkHabitCompleted = `-- name: UnmarkHabitCompleted :exec
DELETE
FROM habit_logs
WHERE habit_id = $1
  AND DATE (completed_at) = DATE ($2)
`

type UnmarkHabitCompletedParams struct {
	HabitID uuid.UUID
	Date    interface{}
}

func (q *Queries) UnmarkHabitCompleted(ctx context.Context, arg UnmarkHabitCompletedParams) error {
	_, err := q.db.ExecContext(ctx, unmarkHabitCompleted, arg.HabitID, arg.Date)
	return err
}

const updateHabit = `-- name: UpdateHabit :one
UPDATE habits
SET name        = COALESCE($1, name),
    description = COALESCE($2, description),
    image_url   = COALESCE($3, image_url)
WHERE id = $4 RETURNING id, user_id, name, description, image_url, created_at
`

type UpdateHabitParams struct {
	Name        sql.NullString
	Description sql.NullString
	ImageUrl    sql.NullString
	ID          uuid.UUID
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) (Habit, error) {
	row := q.db.QueryRowContext(ctx, updateHabit,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.ID,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateRoutine = `-- name: UpdateRoutine :one
UPDATE routines
SET name = COALESCE($1, name)
WHERE id = $2 RETURNING id, user_id, name, created_at
`

type UpdateRoutineParams struct {
	Name sql.NullString
	ID   uuid.UUID
}

func (q *Queries) UpdateRoutine(ctx context.Context, arg UpdateRoutineParams) (Routine, error) {
	row := q.db.QueryRowContext(ctx, updateRoutine, arg.Name, arg.ID)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
