// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/habit/habit.proto

package habit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HabitService_CreateHabit_FullMethodName            = "/habit.HabitService/CreateHabit"
	HabitService_CreateRoutine_FullMethodName          = "/habit.HabitService/CreateRoutine"
	HabitService_GetHabitByID_FullMethodName           = "/habit.HabitService/GetHabitByID"
	HabitService_ListHabitsByUser_FullMethodName       = "/habit.HabitService/ListHabitsByUser"
	HabitService_EditHabit_FullMethodName              = "/habit.HabitService/EditHabit"
	HabitService_DeleteHabit_FullMethodName            = "/habit.HabitService/DeleteHabit"
	HabitService_MarkHabitCompleted_FullMethodName     = "/habit.HabitService/MarkHabitCompleted"
	HabitService_UnmarkHabitCompleted_FullMethodName   = "/habit.HabitService/UnmarkHabitCompleted"
	HabitService_GetHabitLogs_FullMethodName           = "/habit.HabitService/GetHabitLogs"
	HabitService_AddHabitToRoutine_FullMethodName      = "/habit.HabitService/AddHabitToRoutine"
	HabitService_RemoveHabitFromRoutine_FullMethodName = "/habit.HabitService/RemoveHabitFromRoutine"
	HabitService_ListRoutinesByUser_FullMethodName     = "/habit.HabitService/ListRoutinesByUser"
)

// HabitServiceClient is the client API for HabitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HabitServiceClient interface {
	CreateHabit(ctx context.Context, in *CreateHabitRequest, opts ...grpc.CallOption) (*CreateHabitResponse, error)
	CreateRoutine(ctx context.Context, in *CreateRoutineRequest, opts ...grpc.CallOption) (*CreateRoutineResponse, error)
	GetHabitByID(ctx context.Context, in *GetHabitByIDRequest, opts ...grpc.CallOption) (*GetHabitByIDResponse, error)
	ListHabitsByUser(ctx context.Context, in *ListHabitsByUserRequest, opts ...grpc.CallOption) (*ListHabitsByUserResponse, error)
	EditHabit(ctx context.Context, in *EditHabitRequest, opts ...grpc.CallOption) (*EditHabitResponse, error)
	DeleteHabit(ctx context.Context, in *DeleteHabitRequest, opts ...grpc.CallOption) (*DeleteHabitResponse, error)
	MarkHabitCompleted(ctx context.Context, in *MarkHabitCompletedRequest, opts ...grpc.CallOption) (*MarkHabitCompletedResponse, error)
	UnmarkHabitCompleted(ctx context.Context, in *UnmarkHabitCompletedRequest, opts ...grpc.CallOption) (*UnmarkHabitCompletedResponse, error)
	GetHabitLogs(ctx context.Context, in *GetHabitLogsRequest, opts ...grpc.CallOption) (*GetHabitLogsResponse, error)
	AddHabitToRoutine(ctx context.Context, in *AddHabitToRoutineRequest, opts ...grpc.CallOption) (*AddHabitToRoutineResponse, error)
	RemoveHabitFromRoutine(ctx context.Context, in *RemoveHabitFromRoutineRequest, opts ...grpc.CallOption) (*RemoveHabitFromRoutineResponse, error)
	ListRoutinesByUser(ctx context.Context, in *ListRoutinesByUserRequest, opts ...grpc.CallOption) (*ListRoutinesByUserResponse, error)
}

type habitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHabitServiceClient(cc grpc.ClientConnInterface) HabitServiceClient {
	return &habitServiceClient{cc}
}

func (c *habitServiceClient) CreateHabit(ctx context.Context, in *CreateHabitRequest, opts ...grpc.CallOption) (*CreateHabitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHabitResponse)
	err := c.cc.Invoke(ctx, HabitService_CreateHabit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) CreateRoutine(ctx context.Context, in *CreateRoutineRequest, opts ...grpc.CallOption) (*CreateRoutineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoutineResponse)
	err := c.cc.Invoke(ctx, HabitService_CreateRoutine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) GetHabitByID(ctx context.Context, in *GetHabitByIDRequest, opts ...grpc.CallOption) (*GetHabitByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHabitByIDResponse)
	err := c.cc.Invoke(ctx, HabitService_GetHabitByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) ListHabitsByUser(ctx context.Context, in *ListHabitsByUserRequest, opts ...grpc.CallOption) (*ListHabitsByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHabitsByUserResponse)
	err := c.cc.Invoke(ctx, HabitService_ListHabitsByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) EditHabit(ctx context.Context, in *EditHabitRequest, opts ...grpc.CallOption) (*EditHabitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditHabitResponse)
	err := c.cc.Invoke(ctx, HabitService_EditHabit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) DeleteHabit(ctx context.Context, in *DeleteHabitRequest, opts ...grpc.CallOption) (*DeleteHabitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHabitResponse)
	err := c.cc.Invoke(ctx, HabitService_DeleteHabit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) MarkHabitCompleted(ctx context.Context, in *MarkHabitCompletedRequest, opts ...grpc.CallOption) (*MarkHabitCompletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkHabitCompletedResponse)
	err := c.cc.Invoke(ctx, HabitService_MarkHabitCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) UnmarkHabitCompleted(ctx context.Context, in *UnmarkHabitCompletedRequest, opts ...grpc.CallOption) (*UnmarkHabitCompletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnmarkHabitCompletedResponse)
	err := c.cc.Invoke(ctx, HabitService_UnmarkHabitCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) GetHabitLogs(ctx context.Context, in *GetHabitLogsRequest, opts ...grpc.CallOption) (*GetHabitLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHabitLogsResponse)
	err := c.cc.Invoke(ctx, HabitService_GetHabitLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) AddHabitToRoutine(ctx context.Context, in *AddHabitToRoutineRequest, opts ...grpc.CallOption) (*AddHabitToRoutineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddHabitToRoutineResponse)
	err := c.cc.Invoke(ctx, HabitService_AddHabitToRoutine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) RemoveHabitFromRoutine(ctx context.Context, in *RemoveHabitFromRoutineRequest, opts ...grpc.CallOption) (*RemoveHabitFromRoutineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveHabitFromRoutineResponse)
	err := c.cc.Invoke(ctx, HabitService_RemoveHabitFromRoutine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) ListRoutinesByUser(ctx context.Context, in *ListRoutinesByUserRequest, opts ...grpc.CallOption) (*ListRoutinesByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutinesByUserResponse)
	err := c.cc.Invoke(ctx, HabitService_ListRoutinesByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HabitServiceServer is the server API for HabitService service.
// All implementations must embed UnimplementedHabitServiceServer
// for forward compatibility.
type HabitServiceServer interface {
	CreateHabit(context.Context, *CreateHabitRequest) (*CreateHabitResponse, error)
	CreateRoutine(context.Context, *CreateRoutineRequest) (*CreateRoutineResponse, error)
	GetHabitByID(context.Context, *GetHabitByIDRequest) (*GetHabitByIDResponse, error)
	ListHabitsByUser(context.Context, *ListHabitsByUserRequest) (*ListHabitsByUserResponse, error)
	EditHabit(context.Context, *EditHabitRequest) (*EditHabitResponse, error)
	DeleteHabit(context.Context, *DeleteHabitRequest) (*DeleteHabitResponse, error)
	MarkHabitCompleted(context.Context, *MarkHabitCompletedRequest) (*MarkHabitCompletedResponse, error)
	UnmarkHabitCompleted(context.Context, *UnmarkHabitCompletedRequest) (*UnmarkHabitCompletedResponse, error)
	GetHabitLogs(context.Context, *GetHabitLogsRequest) (*GetHabitLogsResponse, error)
	AddHabitToRoutine(context.Context, *AddHabitToRoutineRequest) (*AddHabitToRoutineResponse, error)
	RemoveHabitFromRoutine(context.Context, *RemoveHabitFromRoutineRequest) (*RemoveHabitFromRoutineResponse, error)
	ListRoutinesByUser(context.Context, *ListRoutinesByUserRequest) (*ListRoutinesByUserResponse, error)
	mustEmbedUnimplementedHabitServiceServer()
}

// UnimplementedHabitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHabitServiceServer struct{}

func (UnimplementedHabitServiceServer) CreateHabit(context.Context, *CreateHabitRequest) (*CreateHabitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHabit not implemented")
}
func (UnimplementedHabitServiceServer) CreateRoutine(context.Context, *CreateRoutineRequest) (*CreateRoutineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRoutine not implemented")
}
func (UnimplementedHabitServiceServer) GetHabitByID(context.Context, *GetHabitByIDRequest) (*GetHabitByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHabitByID not implemented")
}
func (UnimplementedHabitServiceServer) ListHabitsByUser(context.Context, *ListHabitsByUserRequest) (*ListHabitsByUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHabitsByUser not implemented")
}
func (UnimplementedHabitServiceServer) EditHabit(context.Context, *EditHabitRequest) (*EditHabitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditHabit not implemented")
}
func (UnimplementedHabitServiceServer) DeleteHabit(context.Context, *DeleteHabitRequest) (*DeleteHabitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHabit not implemented")
}
func (UnimplementedHabitServiceServer) MarkHabitCompleted(context.Context, *MarkHabitCompletedRequest) (*MarkHabitCompletedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkHabitCompleted not implemented")
}
func (UnimplementedHabitServiceServer) UnmarkHabitCompleted(context.Context, *UnmarkHabitCompletedRequest) (*UnmarkHabitCompletedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnmarkHabitCompleted not implemented")
}
func (UnimplementedHabitServiceServer) GetHabitLogs(context.Context, *GetHabitLogsRequest) (*GetHabitLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHabitLogs not implemented")
}
func (UnimplementedHabitServiceServer) AddHabitToRoutine(context.Context, *AddHabitToRoutineRequest) (*AddHabitToRoutineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddHabitToRoutine not implemented")
}
func (UnimplementedHabitServiceServer) RemoveHabitFromRoutine(context.Context, *RemoveHabitFromRoutineRequest) (*RemoveHabitFromRoutineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveHabitFromRoutine not implemented")
}
func (UnimplementedHabitServiceServer) ListRoutinesByUser(context.Context, *ListRoutinesByUserRequest) (*ListRoutinesByUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoutinesByUser not implemented")
}
func (UnimplementedHabitServiceServer) mustEmbedUnimplementedHabitServiceServer() {}
func (UnimplementedHabitServiceServer) testEmbeddedByValue()                      {}

// UnsafeHabitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HabitServiceServer will
// result in compilation errors.
type UnsafeHabitServiceServer interface {
	mustEmbedUnimplementedHabitServiceServer()
}

func RegisterHabitServiceServer(s grpc.ServiceRegistrar, srv HabitServiceServer) {
	// If the following call panics, it indicates UnimplementedHabitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HabitService_ServiceDesc, srv)
}

func _HabitService_CreateHabit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHabitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).CreateHabit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_CreateHabit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).CreateHabit(ctx, req.(*CreateHabitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_CreateRoutine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoutineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).CreateRoutine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_CreateRoutine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).CreateRoutine(ctx, req.(*CreateRoutineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_GetHabitByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHabitByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).GetHabitByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_GetHabitByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).GetHabitByID(ctx, req.(*GetHabitByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_ListHabitsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHabitsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).ListHabitsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_ListHabitsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).ListHabitsByUser(ctx, req.(*ListHabitsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_EditHabit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditHabitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).EditHabit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_EditHabit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).EditHabit(ctx, req.(*EditHabitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_DeleteHabit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHabitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).DeleteHabit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_DeleteHabit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).DeleteHabit(ctx, req.(*DeleteHabitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_MarkHabitCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkHabitCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).MarkHabitCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_MarkHabitCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).MarkHabitCompleted(ctx, req.(*MarkHabitCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_UnmarkHabitCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmarkHabitCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).UnmarkHabitCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_UnmarkHabitCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).UnmarkHabitCompleted(ctx, req.(*UnmarkHabitCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_GetHabitLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHabitLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).GetHabitLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_GetHabitLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).GetHabitLogs(ctx, req.(*GetHabitLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_AddHabitToRoutine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHabitToRoutineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).AddHabitToRoutine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_AddHabitToRoutine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).AddHabitToRoutine(ctx, req.(*AddHabitToRoutineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_RemoveHabitFromRoutine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveHabitFromRoutineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).RemoveHabitFromRoutine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_RemoveHabitFromRoutine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).RemoveHabitFromRoutine(ctx, req.(*RemoveHabitFromRoutineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_ListRoutinesByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutinesByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).ListRoutinesByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_ListRoutinesByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).ListRoutinesByUser(ctx, req.(*ListRoutinesByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HabitService_ServiceDesc is the grpc.ServiceDesc for HabitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HabitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "habit.HabitService",
	HandlerType: (*HabitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHabit",
			Handler:    _HabitService_CreateHabit_Handler,
		},
		{
			MethodName: "CreateRoutine",
			Handler:    _HabitService_CreateRoutine_Handler,
		},
		{
			MethodName: "GetHabitByID",
			Handler:    _HabitService_GetHabitByID_Handler,
		},
		{
			MethodName: "ListHabitsByUser",
			Handler:    _HabitService_ListHabitsByUser_Handler,
		},
		{
			MethodName: "EditHabit",
			Handler:    _HabitService_EditHabit_Handler,
		},
		{
			MethodName: "DeleteHabit",
			Handler:    _HabitService_DeleteHabit_Handler,
		},
		{
			MethodName: "MarkHabitCompleted",
			Handler:    _HabitService_MarkHabitCompleted_Handler,
		},
		{
			MethodName: "UnmarkHabitCompleted",
			Handler:    _HabitService_UnmarkHabitCompleted_Handler,
		},
		{
			MethodName: "GetHabitLogs",
			Handler:    _HabitService_GetHabitLogs_Handler,
		},
		{
			MethodName: "AddHabitToRoutine",
			Handler:    _HabitService_AddHabitToRoutine_Handler,
		},
		{
			MethodName: "RemoveHabitFromRoutine",
			Handler:    _HabitService_RemoveHabitFromRoutine_Handler,
		},
		{
			MethodName: "ListRoutinesByUser",
			Handler:    _HabitService_ListRoutinesByUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/habit/habit.proto",
}
