// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/habit/v4/habit.proto

package habit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Habit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Habit) Reset() {
	*x = Habit{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Habit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Habit) ProtoMessage() {}

func (x *Habit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Habit.ProtoReflect.Descriptor instead.
func (*Habit) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{0}
}

func (x *Habit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Habit) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Habit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Habit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Habit) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Habit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Routine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Routine) Reset() {
	*x = Routine{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Routine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Routine) ProtoMessage() {}

func (x *Routine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Routine.ProtoReflect.Descriptor instead.
func (*Routine) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{1}
}

func (x *Routine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Routine) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Routine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Routine) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type HabitLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HabitLog) Reset() {
	*x = HabitLog{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HabitLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HabitLog) ProtoMessage() {}

func (x *HabitLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HabitLog.ProtoReflect.Descriptor instead.
func (*HabitLog) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{2}
}

func (x *HabitLog) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *HabitLog) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type RoutineLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutineId     string                 `protobuf:"bytes,1,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutineLog) Reset() {
	*x = RoutineLog{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutineLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineLog) ProtoMessage() {}

func (x *RoutineLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineLog.ProtoReflect.Descriptor instead.
func (*RoutineLog) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{3}
}

func (x *RoutineLog) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

func (x *RoutineLog) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type CreateRoutineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routine       *Routine               `protobuf:"bytes,1,opt,name=routine,proto3" json:"routine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoutineRequest) Reset() {
	*x = CreateRoutineRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoutineRequest) ProtoMessage() {}

func (x *CreateRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoutineRequest.ProtoReflect.Descriptor instead.
func (*CreateRoutineRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoutineRequest) GetRoutine() *Routine {
	if x != nil {
		return x.Routine
	}
	return nil
}

type CreateRoutineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routine       *Routine               `protobuf:"bytes,1,opt,name=routine,proto3" json:"routine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoutineResponse) Reset() {
	*x = CreateRoutineResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoutineResponse) ProtoMessage() {}

func (x *CreateRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoutineResponse.ProtoReflect.Descriptor instead.
func (*CreateRoutineResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRoutineResponse) GetRoutine() *Routine {
	if x != nil {
		return x.Routine
	}
	return nil
}

type CreateHabitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habit         *Habit                 `protobuf:"bytes,1,opt,name=habit,proto3" json:"habit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHabitRequest) Reset() {
	*x = CreateHabitRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHabitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHabitRequest) ProtoMessage() {}

func (x *CreateHabitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHabitRequest.ProtoReflect.Descriptor instead.
func (*CreateHabitRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{6}
}

func (x *CreateHabitRequest) GetHabit() *Habit {
	if x != nil {
		return x.Habit
	}
	return nil
}

type CreateHabitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habit         *Habit                 `protobuf:"bytes,1,opt,name=habit,proto3" json:"habit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHabitResponse) Reset() {
	*x = CreateHabitResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHabitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHabitResponse) ProtoMessage() {}

func (x *CreateHabitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHabitResponse.ProtoReflect.Descriptor instead.
func (*CreateHabitResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{7}
}

func (x *CreateHabitResponse) GetHabit() *Habit {
	if x != nil {
		return x.Habit
	}
	return nil
}

type GetHabitByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitByIDRequest) Reset() {
	*x = GetHabitByIDRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitByIDRequest) ProtoMessage() {}

func (x *GetHabitByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitByIDRequest.ProtoReflect.Descriptor instead.
func (*GetHabitByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{8}
}

func (x *GetHabitByIDRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

type GetHabitByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habit         *Habit                 `protobuf:"bytes,1,opt,name=habit,proto3" json:"habit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitByIDResponse) Reset() {
	*x = GetHabitByIDResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitByIDResponse) ProtoMessage() {}

func (x *GetHabitByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitByIDResponse.ProtoReflect.Descriptor instead.
func (*GetHabitByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{9}
}

func (x *GetHabitByIDResponse) GetHabit() *Habit {
	if x != nil {
		return x.Habit
	}
	return nil
}

type ListHabitsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHabitsByUserRequest) Reset() {
	*x = ListHabitsByUserRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHabitsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHabitsByUserRequest) ProtoMessage() {}

func (x *ListHabitsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHabitsByUserRequest.ProtoReflect.Descriptor instead.
func (*ListHabitsByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{10}
}

func (x *ListHabitsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListHabitsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habits        []*Habit               `protobuf:"bytes,1,rep,name=habits,proto3" json:"habits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHabitsByUserResponse) Reset() {
	*x = ListHabitsByUserResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHabitsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHabitsByUserResponse) ProtoMessage() {}

func (x *ListHabitsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHabitsByUserResponse.ProtoReflect.Descriptor instead.
func (*ListHabitsByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{11}
}

func (x *ListHabitsByUserResponse) GetHabits() []*Habit {
	if x != nil {
		return x.Habits
	}
	return nil
}

type ListHabitsByRoutineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutineId     string                 `protobuf:"bytes,1,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHabitsByRoutineRequest) Reset() {
	*x = ListHabitsByRoutineRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHabitsByRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHabitsByRoutineRequest) ProtoMessage() {}

func (x *ListHabitsByRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHabitsByRoutineRequest.ProtoReflect.Descriptor instead.
func (*ListHabitsByRoutineRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{12}
}

func (x *ListHabitsByRoutineRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

type ListHabitsByRoutineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habits        []*Habit               `protobuf:"bytes,1,rep,name=habits,proto3" json:"habits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHabitsByRoutineResponse) Reset() {
	*x = ListHabitsByRoutineResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHabitsByRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHabitsByRoutineResponse) ProtoMessage() {}

func (x *ListHabitsByRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHabitsByRoutineResponse.ProtoReflect.Descriptor instead.
func (*ListHabitsByRoutineResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{13}
}

func (x *ListHabitsByRoutineResponse) GetHabits() []*Habit {
	if x != nil {
		return x.Habits
	}
	return nil
}

type EditHabitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditHabitRequest) Reset() {
	*x = EditHabitRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditHabitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditHabitRequest) ProtoMessage() {}

func (x *EditHabitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditHabitRequest.ProtoReflect.Descriptor instead.
func (*EditHabitRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{14}
}

func (x *EditHabitRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *EditHabitRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EditHabitRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *EditHabitRequest) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

type EditHabitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habit         *Habit                 `protobuf:"bytes,1,opt,name=habit,proto3" json:"habit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditHabitResponse) Reset() {
	*x = EditHabitResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditHabitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditHabitResponse) ProtoMessage() {}

func (x *EditHabitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditHabitResponse.ProtoReflect.Descriptor instead.
func (*EditHabitResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{15}
}

func (x *EditHabitResponse) GetHabit() *Habit {
	if x != nil {
		return x.Habit
	}
	return nil
}

type DeleteHabitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHabitRequest) Reset() {
	*x = DeleteHabitRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHabitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHabitRequest) ProtoMessage() {}

func (x *DeleteHabitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHabitRequest.ProtoReflect.Descriptor instead.
func (*DeleteHabitRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteHabitRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

type DeleteHabitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHabitResponse) Reset() {
	*x = DeleteHabitResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHabitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHabitResponse) ProtoMessage() {}

func (x *DeleteHabitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHabitResponse.ProtoReflect.Descriptor instead.
func (*DeleteHabitResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteHabitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MarkHabitCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkHabitCompletedRequest) Reset() {
	*x = MarkHabitCompletedRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkHabitCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkHabitCompletedRequest) ProtoMessage() {}

func (x *MarkHabitCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkHabitCompletedRequest.ProtoReflect.Descriptor instead.
func (*MarkHabitCompletedRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{18}
}

func (x *MarkHabitCompletedRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *MarkHabitCompletedRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type MarkHabitCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkHabitCompletedResponse) Reset() {
	*x = MarkHabitCompletedResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkHabitCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkHabitCompletedResponse) ProtoMessage() {}

func (x *MarkHabitCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkHabitCompletedResponse.ProtoReflect.Descriptor instead.
func (*MarkHabitCompletedResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{19}
}

func (x *MarkHabitCompletedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnmarkHabitCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmarkHabitCompletedRequest) Reset() {
	*x = UnmarkHabitCompletedRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmarkHabitCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmarkHabitCompletedRequest) ProtoMessage() {}

func (x *UnmarkHabitCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmarkHabitCompletedRequest.ProtoReflect.Descriptor instead.
func (*UnmarkHabitCompletedRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{20}
}

func (x *UnmarkHabitCompletedRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *UnmarkHabitCompletedRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type UnmarkHabitCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmarkHabitCompletedResponse) Reset() {
	*x = UnmarkHabitCompletedResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmarkHabitCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmarkHabitCompletedResponse) ProtoMessage() {}

func (x *UnmarkHabitCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmarkHabitCompletedResponse.ProtoReflect.Descriptor instead.
func (*UnmarkHabitCompletedResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{21}
}

func (x *UnmarkHabitCompletedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetHabitLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitLogsRequest) Reset() {
	*x = GetHabitLogsRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitLogsRequest) ProtoMessage() {}

func (x *GetHabitLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitLogsRequest.ProtoReflect.Descriptor instead.
func (*GetHabitLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{22}
}

func (x *GetHabitLogsRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *GetHabitLogsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetHabitLogsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetHabitLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*HabitLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitLogsResponse) Reset() {
	*x = GetHabitLogsResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitLogsResponse) ProtoMessage() {}

func (x *GetHabitLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitLogsResponse.ProtoReflect.Descriptor instead.
func (*GetHabitLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{23}
}

func (x *GetHabitLogsResponse) GetLogs() []*HabitLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type MarkRoutineCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutineId     string                 `protobuf:"bytes,1,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkRoutineCompletedRequest) Reset() {
	*x = MarkRoutineCompletedRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkRoutineCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRoutineCompletedRequest) ProtoMessage() {}

func (x *MarkRoutineCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRoutineCompletedRequest.ProtoReflect.Descriptor instead.
func (*MarkRoutineCompletedRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{24}
}

func (x *MarkRoutineCompletedRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

func (x *MarkRoutineCompletedRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type MarkRoutineCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkRoutineCompletedResponse) Reset() {
	*x = MarkRoutineCompletedResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkRoutineCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRoutineCompletedResponse) ProtoMessage() {}

func (x *MarkRoutineCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRoutineCompletedResponse.ProtoReflect.Descriptor instead.
func (*MarkRoutineCompletedResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{25}
}

func (x *MarkRoutineCompletedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnmarkRoutineCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutineId     string                 `protobuf:"bytes,1,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmarkRoutineCompletedRequest) Reset() {
	*x = UnmarkRoutineCompletedRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmarkRoutineCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmarkRoutineCompletedRequest) ProtoMessage() {}

func (x *UnmarkRoutineCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmarkRoutineCompletedRequest.ProtoReflect.Descriptor instead.
func (*UnmarkRoutineCompletedRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{26}
}

func (x *UnmarkRoutineCompletedRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

func (x *UnmarkRoutineCompletedRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type UnmarkRoutineCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmarkRoutineCompletedResponse) Reset() {
	*x = UnmarkRoutineCompletedResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmarkRoutineCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmarkRoutineCompletedResponse) ProtoMessage() {}

func (x *UnmarkRoutineCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmarkRoutineCompletedResponse.ProtoReflect.Descriptor instead.
func (*UnmarkRoutineCompletedResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{27}
}

func (x *UnmarkRoutineCompletedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRoutineLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutineId     string                 `protobuf:"bytes,1,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutineLogsRequest) Reset() {
	*x = GetRoutineLogsRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutineLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutineLogsRequest) ProtoMessage() {}

func (x *GetRoutineLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutineLogsRequest.ProtoReflect.Descriptor instead.
func (*GetRoutineLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{28}
}

func (x *GetRoutineLogsRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

func (x *GetRoutineLogsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetRoutineLogsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetRoutineLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*RoutineLog          `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutineLogsResponse) Reset() {
	*x = GetRoutineLogsResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutineLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutineLogsResponse) ProtoMessage() {}

func (x *GetRoutineLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutineLogsResponse.ProtoReflect.Descriptor instead.
func (*GetRoutineLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{29}
}

func (x *GetRoutineLogsResponse) GetLogs() []*RoutineLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type AddHabitToRoutineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	RoutineId     string                 `protobuf:"bytes,2,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHabitToRoutineRequest) Reset() {
	*x = AddHabitToRoutineRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHabitToRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHabitToRoutineRequest) ProtoMessage() {}

func (x *AddHabitToRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHabitToRoutineRequest.ProtoReflect.Descriptor instead.
func (*AddHabitToRoutineRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{30}
}

func (x *AddHabitToRoutineRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *AddHabitToRoutineRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

type AddHabitToRoutineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHabitToRoutineResponse) Reset() {
	*x = AddHabitToRoutineResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHabitToRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHabitToRoutineResponse) ProtoMessage() {}

func (x *AddHabitToRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHabitToRoutineResponse.ProtoReflect.Descriptor instead.
func (*AddHabitToRoutineResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{31}
}

func (x *AddHabitToRoutineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveHabitFromRoutineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	RoutineId     string                 `protobuf:"bytes,2,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveHabitFromRoutineRequest) Reset() {
	*x = RemoveHabitFromRoutineRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveHabitFromRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHabitFromRoutineRequest) ProtoMessage() {}

func (x *RemoveHabitFromRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveHabitFromRoutineRequest.ProtoReflect.Descriptor instead.
func (*RemoveHabitFromRoutineRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{32}
}

func (x *RemoveHabitFromRoutineRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *RemoveHabitFromRoutineRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

type RemoveHabitFromRoutineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveHabitFromRoutineResponse) Reset() {
	*x = RemoveHabitFromRoutineResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveHabitFromRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHabitFromRoutineResponse) ProtoMessage() {}

func (x *RemoveHabitFromRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveHabitFromRoutineResponse.ProtoReflect.Descriptor instead.
func (*RemoveHabitFromRoutineResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{33}
}

func (x *RemoveHabitFromRoutineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListRoutinesByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutinesByUserRequest) Reset() {
	*x = ListRoutinesByUserRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutinesByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutinesByUserRequest) ProtoMessage() {}

func (x *ListRoutinesByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutinesByUserRequest.ProtoReflect.Descriptor instead.
func (*ListRoutinesByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{34}
}

func (x *ListRoutinesByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListRoutinesByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routines      []*Routine             `protobuf:"bytes,1,rep,name=routines,proto3" json:"routines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutinesByUserResponse) Reset() {
	*x = ListRoutinesByUserResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutinesByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutinesByUserResponse) ProtoMessage() {}

func (x *ListRoutinesByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutinesByUserResponse.ProtoReflect.Descriptor instead.
func (*ListRoutinesByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{35}
}

func (x *ListRoutinesByUserResponse) GetRoutines() []*Routine {
	if x != nil {
		return x.Routines
	}
	return nil
}

type GetRoutineByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutineId     string                 `protobuf:"bytes,1,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutineByIDRequest) Reset() {
	*x = GetRoutineByIDRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutineByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutineByIDRequest) ProtoMessage() {}

func (x *GetRoutineByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutineByIDRequest.ProtoReflect.Descriptor instead.
func (*GetRoutineByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{36}
}

func (x *GetRoutineByIDRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

type GetRoutineByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routine       *Routine               `protobuf:"bytes,1,opt,name=routine,proto3" json:"routine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutineByIDResponse) Reset() {
	*x = GetRoutineByIDResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutineByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutineByIDResponse) ProtoMessage() {}

func (x *GetRoutineByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutineByIDResponse.ProtoReflect.Descriptor instead.
func (*GetRoutineByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{37}
}

func (x *GetRoutineByIDResponse) GetRoutine() *Routine {
	if x != nil {
		return x.Routine
	}
	return nil
}

type EditRoutineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutineId     string                 `protobuf:"bytes,1,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditRoutineRequest) Reset() {
	*x = EditRoutineRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditRoutineRequest) ProtoMessage() {}

func (x *EditRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditRoutineRequest.ProtoReflect.Descriptor instead.
func (*EditRoutineRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{38}
}

func (x *EditRoutineRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

func (x *EditRoutineRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type EditRoutineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routine       *Routine               `protobuf:"bytes,1,opt,name=routine,proto3" json:"routine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditRoutineResponse) Reset() {
	*x = EditRoutineResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditRoutineResponse) ProtoMessage() {}

func (x *EditRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditRoutineResponse.ProtoReflect.Descriptor instead.
func (*EditRoutineResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{39}
}

func (x *EditRoutineResponse) GetRoutine() *Routine {
	if x != nil {
		return x.Routine
	}
	return nil
}

type DeleteRoutineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutineId     string                 `protobuf:"bytes,1,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoutineRequest) Reset() {
	*x = DeleteRoutineRequest{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoutineRequest) ProtoMessage() {}

func (x *DeleteRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoutineRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoutineRequest) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{40}
}

func (x *DeleteRoutineRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

type DeleteRoutineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoutineResponse) Reset() {
	*x = DeleteRoutineResponse{}
	mi := &file_proto_habit_v4_habit_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoutineResponse) ProtoMessage() {}

func (x *DeleteRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_habit_v4_habit_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoutineResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoutineResponse) Descriptor() ([]byte, []int) {
	return file_proto_habit_v4_habit_proto_rawDescGZIP(), []int{41}
}

func (x *DeleteRoutineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_habit_v4_habit_proto protoreflect.FileDescriptor

const file_proto_habit_v4_habit_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/habit/v4/habit.proto\x12\x05habit\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n" +
	"\x05Habit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x81\x01\n" +
	"\aRoutine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"d\n" +
	"\bHabitLog\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12=\n" +
	"\fcompleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"j\n" +
	"\n" +
	"RoutineLog\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x01 \x01(\tR\troutineId\x12=\n" +
	"\fcompleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"@\n" +
	"\x14CreateRoutineRequest\x12(\n" +
	"\aroutine\x18\x01 \x01(\v2\x0e.habit.RoutineR\aroutine\"A\n" +
	"\x15CreateRoutineResponse\x12(\n" +
	"\aroutine\x18\x01 \x01(\v2\x0e.habit.RoutineR\aroutine\"8\n" +
	"\x12CreateHabitRequest\x12\"\n" +
	"\x05habit\x18\x01 \x01(\v2\f.habit.HabitR\x05habit\"9\n" +
	"\x13CreateHabitResponse\x12\"\n" +
	"\x05habit\x18\x01 \x01(\v2\f.habit.HabitR\x05habit\"0\n" +
	"\x13GetHabitByIDRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\":\n" +
	"\x14GetHabitByIDResponse\x12\"\n" +
	"\x05habit\x18\x01 \x01(\v2\f.habit.HabitR\x05habit\"2\n" +
	"\x17ListHabitsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x18ListHabitsByUserResponse\x12$\n" +
	"\x06habits\x18\x01 \x03(\v2\f.habit.HabitR\x06habits\";\n" +
	"\x1aListHabitsByRoutineRequest\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x01 \x01(\tR\troutineId\"C\n" +
	"\x1bListHabitsByRoutineResponse\x12$\n" +
	"\x06habits\x18\x01 \x03(\v2\f.habit.HabitR\x06habits\"\xb6\x01\n" +
	"\x10EditHabitRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12 \n" +
	"\timage_url\x18\x04 \x01(\tH\x02R\bimageUrl\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_image_url\"7\n" +
	"\x11EditHabitResponse\x12\"\n" +
	"\x05habit\x18\x01 \x01(\v2\f.habit.HabitR\x05habit\"/\n" +
	"\x12DeleteHabitRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\"/\n" +
	"\x13DeleteHabitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"u\n" +
	"\x19MarkHabitCompletedRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12=\n" +
	"\fcompleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"6\n" +
	"\x1aMarkHabitCompletedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"w\n" +
	"\x1bUnmarkHabitCompletedRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12=\n" +
	"\fcompleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"8\n" +
	"\x1cUnmarkHabitCompletedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa2\x01\n" +
	"\x13GetHabitLogsRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\";\n" +
	"\x14GetHabitLogsResponse\x12#\n" +
	"\x04logs\x18\x01 \x03(\v2\x0f.habit.HabitLogR\x04logs\"{\n" +
	"\x1bMarkRoutineCompletedRequest\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x01 \x01(\tR\troutineId\x12=\n" +
	"\fcompleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"8\n" +
	"\x1cMarkRoutineCompletedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"}\n" +
	"\x1dUnmarkRoutineCompletedRequest\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x01 \x01(\tR\troutineId\x12=\n" +
	"\fcompleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\":\n" +
	"\x1eUnmarkRoutineCompletedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa8\x01\n" +
	"\x15GetRoutineLogsRequest\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x01 \x01(\tR\troutineId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"?\n" +
	"\x16GetRoutineLogsResponse\x12%\n" +
	"\x04logs\x18\x01 \x03(\v2\x11.habit.RoutineLogR\x04logs\"T\n" +
	"\x18AddHabitToRoutineRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x02 \x01(\tR\troutineId\"5\n" +
	"\x19AddHabitToRoutineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Y\n" +
	"\x1dRemoveHabitFromRoutineRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x02 \x01(\tR\troutineId\":\n" +
	"\x1eRemoveHabitFromRoutineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x19ListRoutinesByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"H\n" +
	"\x1aListRoutinesByUserResponse\x12*\n" +
	"\broutines\x18\x01 \x03(\v2\x0e.habit.RoutineR\broutines\"6\n" +
	"\x15GetRoutineByIDRequest\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x01 \x01(\tR\troutineId\"B\n" +
	"\x16GetRoutineByIDResponse\x12(\n" +
	"\aroutine\x18\x01 \x01(\v2\x0e.habit.RoutineR\aroutine\"U\n" +
	"\x12EditRoutineRequest\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x01 \x01(\tR\troutineId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"?\n" +
	"\x13EditRoutineResponse\x12(\n" +
	"\aroutine\x18\x01 \x01(\v2\x0e.habit.RoutineR\aroutine\"5\n" +
	"\x14DeleteRoutineRequest\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x01 \x01(\tR\troutineId\"1\n" +
	"\x15DeleteRoutineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xdb\x05\n" +
	"\fHabitService\x12D\n" +
	"\vCreateHabit\x12\x19.habit.CreateHabitRequest\x1a\x1a.habit.CreateHabitResponse\x12G\n" +
	"\fGetHabitByID\x12\x1a.habit.GetHabitByIDRequest\x1a\x1b.habit.GetHabitByIDResponse\x12S\n" +
	"\x10ListHabitsByUser\x12\x1e.habit.ListHabitsByUserRequest\x1a\x1f.habit.ListHabitsByUserResponse\x12\\\n" +
	"\x13ListHabitsByRoutine\x12!.habit.ListHabitsByRoutineRequest\x1a\".habit.ListHabitsByRoutineResponse\x12>\n" +
	"\tEditHabit\x12\x17.habit.EditHabitRequest\x1a\x18.habit.EditHabitResponse\x12D\n" +
	"\vDeleteHabit\x12\x19.habit.DeleteHabitRequest\x1a\x1a.habit.DeleteHabitResponse\x12Y\n" +
	"\x12MarkHabitCompleted\x12 .habit.MarkHabitCompletedRequest\x1a!.habit.MarkHabitCompletedResponse\x12_\n" +
	"\x14UnmarkHabitCompleted\x12\".habit.UnmarkHabitCompletedRequest\x1a#.habit.UnmarkHabitCompletedResponse\x12G\n" +
	"\fGetHabitLogs\x12\x1a.habit.GetHabitLogsRequest\x1a\x1b.habit.GetHabitLogsResponse2\xee\x06\n" +
	"\x0eRoutineService\x12J\n" +
	"\rCreateRoutine\x12\x1b.habit.CreateRoutineRequest\x1a\x1c.habit.CreateRoutineResponse\x12M\n" +
	"\x0eGetRoutineByID\x12\x1c.habit.GetRoutineByIDRequest\x1a\x1d.habit.GetRoutineByIDResponse\x12D\n" +
	"\vEditRoutine\x12\x19.habit.EditRoutineRequest\x1a\x1a.habit.EditRoutineResponse\x12J\n" +
	"\rDeleteRoutine\x12\x1b.habit.DeleteRoutineRequest\x1a\x1c.habit.DeleteRoutineResponse\x12V\n" +
	"\x11AddHabitToRoutine\x12\x1f.habit.AddHabitToRoutineRequest\x1a .habit.AddHabitToRoutineResponse\x12e\n" +
	"\x16RemoveHabitFromRoutine\x12$.habit.RemoveHabitFromRoutineRequest\x1a%.habit.RemoveHabitFromRoutineResponse\x12Y\n" +
	"\x12ListRoutinesByUser\x12 .habit.ListRoutinesByUserRequest\x1a!.habit.ListRoutinesByUserResponse\x12_\n" +
	"\x14MarkRoutineCompleted\x12\".habit.MarkRoutineCompletedRequest\x1a#.habit.MarkRoutineCompletedResponse\x12e\n" +
	"\x16UnmarkRoutineCompleted\x12$.habit.UnmarkRoutineCompletedRequest\x1a%.habit.UnmarkRoutineCompletedResponse\x12M\n" +
	"\x0eGetRoutineLogs\x12\x1c.habit.GetRoutineLogsRequest\x1a\x1d.habit.GetRoutineLogsResponseB\n" +
	"Z\bpb/habitb\x06proto3"

var (
	file_proto_habit_v4_habit_proto_rawDescOnce sync.Once
	file_proto_habit_v4_habit_proto_rawDescData []byte
)

func file_proto_habit_v4_habit_proto_rawDescGZIP() []byte {
	file_proto_habit_v4_habit_proto_rawDescOnce.Do(func() {
		file_proto_habit_v4_habit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_habit_v4_habit_proto_rawDesc), len(file_proto_habit_v4_habit_proto_rawDesc)))
	})
	return file_proto_habit_v4_habit_proto_rawDescData
}

var file_proto_habit_v4_habit_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_proto_habit_v4_habit_proto_goTypes = []any{
	(*Habit)(nil),                          // 0: habit.Habit
	(*Routine)(nil),                        // 1: habit.Routine
	(*HabitLog)(nil),                       // 2: habit.HabitLog
	(*RoutineLog)(nil),                     // 3: habit.RoutineLog
	(*CreateRoutineRequest)(nil),           // 4: habit.CreateRoutineRequest
	(*CreateRoutineResponse)(nil),          // 5: habit.CreateRoutineResponse
	(*CreateHabitRequest)(nil),             // 6: habit.CreateHabitRequest
	(*CreateHabitResponse)(nil),            // 7: habit.CreateHabitResponse
	(*GetHabitByIDRequest)(nil),            // 8: habit.GetHabitByIDRequest
	(*GetHabitByIDResponse)(nil),           // 9: habit.GetHabitByIDResponse
	(*ListHabitsByUserRequest)(nil),        // 10: habit.ListHabitsByUserRequest
	(*ListHabitsByUserResponse)(nil),       // 11: habit.ListHabitsByUserResponse
	(*ListHabitsByRoutineRequest)(nil),     // 12: habit.ListHabitsByRoutineRequest
	(*ListHabitsByRoutineResponse)(nil),    // 13: habit.ListHabitsByRoutineResponse
	(*EditHabitRequest)(nil),               // 14: habit.EditHabitRequest
	(*EditHabitResponse)(nil),              // 15: habit.EditHabitResponse
	(*DeleteHabitRequest)(nil),             // 16: habit.DeleteHabitRequest
	(*DeleteHabitResponse)(nil),            // 17: habit.DeleteHabitResponse
	(*MarkHabitCompletedRequest)(nil),      // 18: habit.MarkHabitCompletedRequest
	(*MarkHabitCompletedResponse)(nil),     // 19: habit.MarkHabitCompletedResponse
	(*UnmarkHabitCompletedRequest)(nil),    // 20: habit.UnmarkHabitCompletedRequest
	(*UnmarkHabitCompletedResponse)(nil),   // 21: habit.UnmarkHabitCompletedResponse
	(*GetHabitLogsRequest)(nil),            // 22: habit.GetHabitLogsRequest
	(*GetHabitLogsResponse)(nil),           // 23: habit.GetHabitLogsResponse
	(*MarkRoutineCompletedRequest)(nil),    // 24: habit.MarkRoutineCompletedRequest
	(*MarkRoutineCompletedResponse)(nil),   // 25: habit.MarkRoutineCompletedResponse
	(*UnmarkRoutineCompletedRequest)(nil),  // 26: habit.UnmarkRoutineCompletedRequest
	(*UnmarkRoutineCompletedResponse)(nil), // 27: habit.UnmarkRoutineCompletedResponse
	(*GetRoutineLogsRequest)(nil),          // 28: habit.GetRoutineLogsRequest
	(*GetRoutineLogsResponse)(nil),         // 29: habit.GetRoutineLogsResponse
	(*AddHabitToRoutineRequest)(nil),       // 30: habit.AddHabitToRoutineRequest
	(*AddHabitToRoutineResponse)(nil),      // 31: habit.AddHabitToRoutineResponse
	(*RemoveHabitFromRoutineRequest)(nil),  // 32: habit.RemoveHabitFromRoutineRequest
	(*RemoveHabitFromRoutineResponse)(nil), // 33: habit.RemoveHabitFromRoutineResponse
	(*ListRoutinesByUserRequest)(nil),      // 34: habit.ListRoutinesByUserRequest
	(*ListRoutinesByUserResponse)(nil),     // 35: habit.ListRoutinesByUserResponse
	(*GetRoutineByIDRequest)(nil),          // 36: habit.GetRoutineByIDRequest
	(*GetRoutineByIDResponse)(nil),         // 37: habit.GetRoutineByIDResponse
	(*EditRoutineRequest)(nil),             // 38: habit.EditRoutineRequest
	(*EditRoutineResponse)(nil),            // 39: habit.EditRoutineResponse
	(*DeleteRoutineRequest)(nil),           // 40: habit.DeleteRoutineRequest
	(*DeleteRoutineResponse)(nil),          // 41: habit.DeleteRoutineResponse
	(*timestamppb.Timestamp)(nil),          // 42: google.protobuf.Timestamp
}
var file_proto_habit_v4_habit_proto_depIdxs = []int32{
	42, // 0: habit.Habit.created_at:type_name -> google.protobuf.Timestamp
	42, // 1: habit.Routine.created_at:type_name -> google.protobuf.Timestamp
	42, // 2: habit.HabitLog.completed_at:type_name -> google.protobuf.Timestamp
	42, // 3: habit.RoutineLog.completed_at:type_name -> google.protobuf.Timestamp
	1,  // 4: habit.CreateRoutineRequest.routine:type_name -> habit.Routine
	1,  // 5: habit.CreateRoutineResponse.routine:type_name -> habit.Routine
	0,  // 6: habit.CreateHabitRequest.habit:type_name -> habit.Habit
	0,  // 7: habit.CreateHabitResponse.habit:type_name -> habit.Habit
	0,  // 8: habit.GetHabitByIDResponse.habit:type_name -> habit.Habit
	0,  // 9: habit.ListHabitsByUserResponse.habits:type_name -> habit.Habit
	0,  // 10: habit.ListHabitsByRoutineResponse.habits:type_name -> habit.Habit
	0,  // 11: habit.EditHabitResponse.habit:type_name -> habit.Habit
	42, // 12: habit.MarkHabitCompletedRequest.completed_at:type_name -> google.protobuf.Timestamp
	42, // 13: habit.UnmarkHabitCompletedRequest.completed_at:type_name -> google.protobuf.Timestamp
	42, // 14: habit.GetHabitLogsRequest.start_date:type_name -> google.protobuf.Timestamp
	42, // 15: habit.GetHabitLogsRequest.end_date:type_name -> google.protobuf.Timestamp
	2,  // 16: habit.GetHabitLogsResponse.logs:type_name -> habit.HabitLog
	42, // 17: habit.MarkRoutineCompletedRequest.completed_at:type_name -> google.protobuf.Timestamp
	42, // 18: habit.UnmarkRoutineCompletedRequest.completed_at:type_name -> google.protobuf.Timestamp
	42, // 19: habit.GetRoutineLogsRequest.start_date:type_name -> google.protobuf.Timestamp
	42, // 20: habit.GetRoutineLogsRequest.end_date:type_name -> google.protobuf.Timestamp
	3,  // 21: habit.GetRoutineLogsResponse.logs:type_name -> habit.RoutineLog
	1,  // 22: habit.ListRoutinesByUserResponse.routines:type_name -> habit.Routine
	1,  // 23: habit.GetRoutineByIDResponse.routine:type_name -> habit.Routine
	1,  // 24: habit.EditRoutineResponse.routine:type_name -> habit.Routine
	6,  // 25: habit.HabitService.CreateHabit:input_type -> habit.CreateHabitRequest
	8,  // 26: habit.HabitService.GetHabitByID:input_type -> habit.GetHabitByIDRequest
	10, // 27: habit.HabitService.ListHabitsByUser:input_type -> habit.ListHabitsByUserRequest
	12, // 28: habit.HabitService.ListHabitsByRoutine:input_type -> habit.ListHabitsByRoutineRequest
	14, // 29: habit.HabitService.EditHabit:input_type -> habit.EditHabitRequest
	16, // 30: habit.HabitService.DeleteHabit:input_type -> habit.DeleteHabitRequest
	18, // 31: habit.HabitService.MarkHabitCompleted:input_type -> habit.MarkHabitCompletedRequest
	20, // 32: habit.HabitService.UnmarkHabitCompleted:input_type -> habit.UnmarkHabitCompletedRequest
	22, // 33: habit.HabitService.GetHabitLogs:input_type -> habit.GetHabitLogsRequest
	4,  // 34: habit.RoutineService.CreateRoutine:input_type -> habit.CreateRoutineRequest
	36, // 35: habit.RoutineService.GetRoutineByID:input_type -> habit.GetRoutineByIDRequest
	38, // 36: habit.RoutineService.EditRoutine:input_type -> habit.EditRoutineRequest
	40, // 37: habit.RoutineService.DeleteRoutine:input_type -> habit.DeleteRoutineRequest
	30, // 38: habit.RoutineService.AddHabitToRoutine:input_type -> habit.AddHabitToRoutineRequest
	32, // 39: habit.RoutineService.RemoveHabitFromRoutine:input_type -> habit.RemoveHabitFromRoutineRequest
	34, // 40: habit.RoutineService.ListRoutinesByUser:input_type -> habit.ListRoutinesByUserRequest
	24, // 41: habit.RoutineService.MarkRoutineCompleted:input_type -> habit.MarkRoutineCompletedRequest
	26, // 42: habit.RoutineService.UnmarkRoutineCompleted:input_type -> habit.UnmarkRoutineCompletedRequest
	28, // 43: habit.RoutineService.GetRoutineLogs:input_type -> habit.GetRoutineLogsRequest
	7,  // 44: habit.HabitService.CreateHabit:output_type -> habit.CreateHabitResponse
	9,  // 45: habit.HabitService.GetHabitByID:output_type -> habit.GetHabitByIDResponse
	11, // 46: habit.HabitService.ListHabitsByUser:output_type -> habit.ListHabitsByUserResponse
	13, // 47: habit.HabitService.ListHabitsByRoutine:output_type -> habit.ListHabitsByRoutineResponse
	15, // 48: habit.HabitService.EditHabit:output_type -> habit.EditHabitResponse
	17, // 49: habit.HabitService.DeleteHabit:output_type -> habit.DeleteHabitResponse
	19, // 50: habit.HabitService.MarkHabitCompleted:output_type -> habit.MarkHabitCompletedResponse
	21, // 51: habit.HabitService.UnmarkHabitCompleted:output_type -> habit.UnmarkHabitCompletedResponse
	23, // 52: habit.HabitService.GetHabitLogs:output_type -> habit.GetHabitLogsResponse
	5,  // 53: habit.RoutineService.CreateRoutine:output_type -> habit.CreateRoutineResponse
	37, // 54: habit.RoutineService.GetRoutineByID:output_type -> habit.GetRoutineByIDResponse
	39, // 55: habit.RoutineService.EditRoutine:output_type -> habit.EditRoutineResponse
	41, // 56: habit.RoutineService.DeleteRoutine:output_type -> habit.DeleteRoutineResponse
	31, // 57: habit.RoutineService.AddHabitToRoutine:output_type -> habit.AddHabitToRoutineResponse
	33, // 58: habit.RoutineService.RemoveHabitFromRoutine:output_type -> habit.RemoveHabitFromRoutineResponse
	35, // 59: habit.RoutineService.ListRoutinesByUser:output_type -> habit.ListRoutinesByUserResponse
	25, // 60: habit.RoutineService.MarkRoutineCompleted:output_type -> habit.MarkRoutineCompletedResponse
	27, // 61: habit.RoutineService.UnmarkRoutineCompleted:output_type -> habit.UnmarkRoutineCompletedResponse
	29, // 62: habit.RoutineService.GetRoutineLogs:output_type -> habit.GetRoutineLogsResponse
	44, // [44:63] is the sub-list for method output_type
	25, // [25:44] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_habit_v4_habit_proto_init() }
func file_proto_habit_v4_habit_proto_init() {
	if File_proto_habit_v4_habit_proto != nil {
		return
	}
	file_proto_habit_v4_habit_proto_msgTypes[14].OneofWrappers = []any{}
	file_proto_habit_v4_habit_proto_msgTypes[38].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_habit_v4_habit_proto_rawDesc), len(file_proto_habit_v4_habit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_habit_v4_habit_proto_goTypes,
		DependencyIndexes: file_proto_habit_v4_habit_proto_depIdxs,
		MessageInfos:      file_proto_habit_v4_habit_proto_msgTypes,
	}.Build()
	File_proto_habit_v4_habit_proto = out.File
	file_proto_habit_v4_habit_proto_goTypes = nil
	file_proto_habit_v4_habit_proto_depIdxs = nil
}
