// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Follow struct {
	ID         int32
	FollowerID int32
	FolloweeID int32
	CreatedAt  sql.NullTime
}
