// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const listFollowers = `-- name: ListFollowers :many
SELECT follower_id
FROM follows
WHERE followee_id = ?
`

func (q *Queries) ListFollowers(ctx context.Context, followeeID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, listFollowers, followeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var follower_id int32
		if err := rows.Scan(&follower_id); err != nil {
			return nil, err
		}
		items = append(items, follower_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT followee_id
FROM follows
WHERE follower_id = ?
`

func (q *Queries) ListFollowing(ctx context.Context, followerID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, listFollowing, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var followee_id int32
		if err := rows.Scan(&followee_id); err != nil {
			return nil, err
		}
		items = append(items, followee_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startFollowing = `-- name: StartFollowing :exec
INSERT INTO follows (follower_id, followee_id)
VALUES (?, ?)
`

type StartFollowingParams struct {
	FollowerID int32
	FolloweeID int32
}

func (q *Queries) StartFollowing(ctx context.Context, arg StartFollowingParams) error {
	_, err := q.db.ExecContext(ctx, startFollowing, arg.FollowerID, arg.FolloweeID)
	return err
}

const unfollow = `-- name: Unfollow :exec
DELETE FROM follows
WHERE follower_id = ? AND followee_id = ?
`

type UnfollowParams struct {
	FollowerID int32
	FolloweeID int32
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.ExecContext(ctx, unfollow, arg.FollowerID, arg.FolloweeID)
	return err
}
