version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  auth-service:
    restart: unless-stopped
    env_file:
      - ../../../auth-services-node/.env
    build: ../../../auth-services-node
    ports:
      - "3000:3000"
    depends_on:
      - redis

  user-service:
    restart: unless-stopped
    env_file:
      - ../../../services/user-service/.env
    build:
      context: ../../../services/user-service
      dockerfile: Dockerfile.dev

    volumes:
      - ../../../services/user-service:/app

    ports:
      - "8080:8080"

  social-service:
    restart: unless-stopped
    env_file:
      - ../../../services/social-service/.env

    build:
      context: ../../../services/social-service
      dockerfile: Dockerfile.dev

    volumes:
      - ../../../services/social-service:/app

    ports:
      - "8081:8081"

    depends_on:
      - user-service


