version: "3.9"

services:
  redis:
    image: redis:7
    restart: unless-stopped

  auth-service:
    restart: unless-stopped
    build:
      context: ../../../auth-services-node
      dockerfile: Dockerfile
    env_file:
      - ../../../auth-services-node/.env
    depends_on:
      - redis

  user-service:
    restart: unless-stopped
    env_file:
      - ../../../services/user-service/.env
    build:
      context: ../../../
      dockerfile: services/user-service/Dockerfile

  social-service:
    restart: unless-stopped
    env_file:
      - ../../../services/social-service/.env

    build:
      context: ../../../
      dockerfile: services/social-service/Dockerfile

    depends_on:
      - user-service

  habit-service:
    restart: unless-stopped
    env_file:
      - ../../../services/habit-service/.env

    build:
      context: ../../../
      dockerfile: services/habit-service/Dockerfile

    depends_on:
      - user-service
    
  stats-service:
    restart: unless-stopped
    env_file:
      - ../../../services/stats-service/.env

    build:
      context: ../../../
      dockerfile: services/stats-service/Dockerfile

    depends_on:
      - user-service
      - habit-service


  nginx:
    build:
      context: ../../nginx

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - auth-service
      - user-service
      - social-service
      - habit-service
      - stats-service
