syntax = "proto3";

package social;

option go_package = "pb/social";

message User {
  string id = 1;
  string name = 2;
  string email = 3;
}

message Follow {
  string follower_id = 1;
  string followee_id = 2;
}

message StartFollowingRequest {
  string follower_id = 1;
  string followee_id = 2;
}

message StartFollowingResponse {
  bool success = 1;
}

message UnfollowRequest {
  string follower_id = 1;
  string followee_id = 2;
}

message UnfollowResponse {
  bool success = 1;
}

message ListFollowersRequest {
  string user_id = 1;
}

message ListFollowersResponse {
  repeated User users = 1;
}

message ListFollowingRequest {
  string user_id = 1;
}

message ListFollowingResponse {
  repeated User users = 1;
}

service SocialService {
  rpc StartFollowing(StartFollowingRequest) returns (StartFollowingResponse);
  rpc Unfollow(UnfollowRequest) returns (UnfollowResponse);
  rpc ListFollowers(ListFollowersRequest) returns (ListFollowersResponse);
  rpc ListFollowing(ListFollowingRequest) returns (ListFollowingResponse);
}